---
resource_types:
- name: slack-notifier
  type: registry-image
  source: {repository: mockersf/concourse-slack-notifier}

jobs:
- name: build-image
  public: true
  plan:
  - in_parallel:
    - get: baggageclaim-image-building
      trigger: true
    - get: golang-1.x
      trigger: true
    - get: ci
    - get: oci-build-task
  - task: build
    image: oci-build-task
    privileged: true
    file: baggageclaim-image-building/ci/build-image.yml
    input_mapping: {baggageclaim-dockerfile: baggageclaim-image-building}
  - put: baggageclaim-ci-image
    params: {image: image/image.tar}
  on_failure:
    do:
    - task: format-slack-message
      file: ci/tasks/format-slack-message.yml
      input_mapping: {src: baggageclaim-image-building}
      params:
        GITHUB_TOKEN: ((concourse_github_dummy.access_token))
        SLACK_TOKEN: ((slack_token))
        GITHUB_REPO: baggageclaim
    - put: notify
      params:
        message_file: message/message
        mode: normal
        alert_type: failed
- name: baggageclaim
  public: true
  serial: true
  plan:
  - in_parallel:
    - get: baggageclaim
      trigger: true
    - get: baggageclaim-ci-image
      passed: [build-image]
    - get: ci
  - in_parallel:
    - task: unit-linux
      image: baggageclaim-ci-image
      privileged: true
      file: baggageclaim/ci/unit-linux.yml
    - task: unit-darwin
      file: baggageclaim/ci/unit-darwin.yml
    - task: unit-windows
      file: baggageclaim/ci/unit-windows.yml
  on_failure:
    do:
    - task: format-slack-message
      file: ci/tasks/format-slack-message.yml
      input_mapping: {src: baggageclaim}
      params:
        GITHUB_TOKEN: ((concourse_github_dummy.access_token))
        SLACK_TOKEN: ((slack_token))
        GITHUB_REPO: baggageclaim
    - put: notify
      params:
        message_file: message/message
        mode: normal
        alert_type: failed

resources:
- name: baggageclaim
  type: git
  source:
    uri: https://github.com/concourse/baggageclaim.git
    branch: master
  icon: &git-icon github-circle
- name: baggageclaim-image-building
  type: git
  source:
    uri: https://github.com/concourse/baggageclaim.git
    branch: master
    paths:
    - Dockerfile
    - ci/build-image.yml
  icon: *git-icon
- name: ci
  type: git
  icon: *git-icon
  source:
    uri: https://github.com/concourse/ci.git
    branch: master
- name: baggageclaim-ci-image
  type: registry-image
  source:
    repository: concourse/baggageclaim-ci
    password: ((docker.password))
    username: ((docker.username))
  icon: docker
- name: golang-1.x
  type: registry-image
  source:
    repository: golang
    tag: 1
  icon: language-go
- name: oci-build-task
  type: registry-image
  icon: docker
  source: {repository: vito/oci-build-task}
- name: notify
  type: slack-notifier
  icon: slack
  source:
    url: ((slack_hook))
