#!/bin/bash
# vim: set ft=sh

set -e -x

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

cd baggageclaim

go mod download

go install github.com/onsi/ginkgo/ginkgo

ginkgo -r -race -nodes 4 --failOnPending --randomizeAllSpecs --keepGoing -skip=":skip" "$@"
