#!/bin/sh

templates=$(dirname $0)/templates

infrastructure=$1

shift

if [ "$infrastructure" != "aws" ] && [ "$infrastructure" != "warden" ] && [ "$infrastructure" != "workstation" ]; then
  echo "usage: ./generate_deployment_manifest <aws|warden> [stubs...]"
  exit 1
fi

spiff merge \
  $templates/deployment.yml \
  $templates/jobs.yml \
  $templates/infrastructure-${infrastructure}.yml \
  $*
