jobs:
  - name: hello-services
    plan:
      - task: say-hi-with-a-service
        services:
          - name: redis
            config:
              platform: linux
              image_resource:
                type: registry-image
                source:
                  repository: redis
              run:
                path: '/usr/local/bin/redis-server'
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: alpine
          run:
            path: echo
            args: [ "Hello, not service!" ]