jobs:
  - name: hello-services
    plan:
      - task: say-hi-with-a-service
        services:
          - name: hello-service
            config:
              platform: linux
              image_resource:
                type: registry-image
                source:
                  repository: alpine
              run:
                path: echo
                args: [ "Hello, services!" ]
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: alpine
          run:
            path: echo
            args: [ "Hello, not service!" ]