resources:
  - name: xvp
    type: git
    icon: github
    webhook_token: ((github-enterprise.webhook-token))
    check_every: 168h
    source:
      uri: git@github.comcast.com:xvp/xvp
      branch: concourse-services-rfc
      private_key: ((xvp-service-account.private-key))

jobs:
  - name: hello-services
    plan:
      - get: xvp
      - task: session-api-integration-test
        services:
          - name: redis
            config:
              platform: linux
              image_resource:
                type: registry-image
                source:
                  repository: redis
              ports:
                - name: default
                  number: 6379
              run:
                path: '/usr/local/bin/redis-server'
          - name: scylla
            config:
              platform: linux
              image_resource:
                type: registry-image
                source:
                  repository: scylladb/scylla
              ports:
                - name: default
                  number: 7199
              run:
                path: '/docker-entrypoint.py'

        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: amazoncorretto
              tag: 17
          inputs:
            - name: xvp
          params:
            AWS_ACCESS_KEY_ID: ((aws-iam-svc-concourse.access-key-id))
            AWS_SECRET_ACCESS_KEY: ((aws-iam-svc-concourse.secret-access-key))
            XVP_SAT_CLIENTID: ((xvp-sats.id))
            XVP_SAT_CLIENTSECRET: ((xvp-sats.secret))
            CASS_USERNAME: ((xvp-parental-dev-cassandra.username))
            CASS_PASSWORD: ((xvp-parental-dev-cassandra.password))
            CASS_TRUSTSTORE_JKS: ((xvp-parental-dev-cassandra.truststore-jks-base64))
            CASS_TRUSTSTORE_PASSWORD: ((xvp-parental-dev-cassandra.truststore-password))
            CASS_KEYSTORE_JKS: ((xvp-parental-dev-cassandra.keystore-jks-base64))
            CASS_KEYSTORE_PASSWORD: ((xvp-parental-dev-cassandra.keystore-password))
            DVR_ARTIFACTORY_USERNAME: ((dvr-artifactory.username))
            DVR_ARTIFACTORY_PASSWORD: ((dvr-artifactory.password))
            REDIS_HOST: ((.svc:redis.host))
            SCYLLA_HOST: ((.svc:scylla.host))
          caches:
            - path: gradle
          run:
            path: sh
            dir: xvp
            args:
              - -exc
              - |
                echo $REDIS_HOST
                echo $SCYLLA_HOST
                export SPRING_PROFILES_ACTIVE="test"
                export GRADLE_USER_HOME="$(pwd)/../gradle"
                ./gradlew services:session-api:integrationTest
                
