jobs:
  - name: hello-services
    plan:
      - task: say-hi-with-a-service
        services:
          - name: redis
            config:
              platform: linux
              image_resource:
                type: registry-image
                source:
                  repository: redis
              ports:
                - name: default
                  number: 6379
              run:
                path: '/usr/local/bin/redis-server'
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: redis
          run:
            path: sh
            args:
              - -exc
              - |
                sleep 10000