// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/concourse/atc/db"
)

type FakeTeamDBFactory struct {
	GetTeamDBStub        func(string) db.TeamDB
	getTeamDBMutex       sync.RWMutex
	getTeamDBArgsForCall []struct {
		arg1 string
	}
	getTeamDBReturns struct {
		result1 db.TeamDB
	}
}

func (fake *FakeTeamDBFactory) GetTeamDB(arg1 string) db.TeamDB {
	fake.getTeamDBMutex.Lock()
	fake.getTeamDBArgsForCall = append(fake.getTeamDBArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.getTeamDBMutex.Unlock()
	if fake.GetTeamDBStub != nil {
		return fake.GetTeamDBStub(arg1)
	} else {
		return fake.getTeamDBReturns.result1
	}
}

func (fake *FakeTeamDBFactory) GetTeamDBCallCount() int {
	fake.getTeamDBMutex.RLock()
	defer fake.getTeamDBMutex.RUnlock()
	return len(fake.getTeamDBArgsForCall)
}

func (fake *FakeTeamDBFactory) GetTeamDBArgsForCall(i int) string {
	fake.getTeamDBMutex.RLock()
	defer fake.getTeamDBMutex.RUnlock()
	return fake.getTeamDBArgsForCall[i].arg1
}

func (fake *FakeTeamDBFactory) GetTeamDBReturns(result1 db.TeamDB) {
	fake.GetTeamDBStub = nil
	fake.getTeamDBReturns = struct {
		result1 db.TeamDB
	}{result1}
}

var _ db.TeamDBFactory = new(FakeTeamDBFactory)
