---
jobs:
- name: some-job
  plan:
  - task: wait
    config:
      platform: linux
      image_resource:
        type: mock
        source:
          mirror_self: true
          initial_version: pipeline-image-1
      run:
        path: sh
        args:
        - -c
        - |
          until test -f /tmp/stop-waiting; do
            echo 'waiting for /tmp/stop-waiting to exist'
            sleep 1
          done

          echo done
