#!/bin/bash

set -e -u

cd $(dirname $0)

echo 'generating certs...'
rm -rf certs
certstrap --depot-path certs init --cn vault-ca --passphrase ''
certstrap --depot-path certs request-cert --domain vault --ip 127.0.0.1 --passphrase ''
certstrap --depot-path certs sign vault --CA vault-ca --passphrase ''
certstrap --depot-path certs request-cert --cn concourse --passphrase ''
certstrap --depot-path certs sign concourse --CA vault-ca --passphrase ''
