// This file was generated by counterfeiter
package resourceserverfakes

import (
	"sync"

	"github.com/concourse/atc/api/resourceserver"
	"github.com/concourse/atc/dbng"
	"github.com/concourse/atc/radar"
)

type FakeScannerFactory struct {
	NewResourceScannerStub        func(pipeline dbng.Pipeline) radar.Scanner
	newResourceScannerMutex       sync.RWMutex
	newResourceScannerArgsForCall []struct {
		pipeline dbng.Pipeline
	}
	newResourceScannerReturns struct {
		result1 radar.Scanner
	}
	newResourceScannerReturnsOnCall map[int]struct {
		result1 radar.Scanner
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeScannerFactory) NewResourceScanner(pipeline dbng.Pipeline) radar.Scanner {
	fake.newResourceScannerMutex.Lock()
	ret, specificReturn := fake.newResourceScannerReturnsOnCall[len(fake.newResourceScannerArgsForCall)]
	fake.newResourceScannerArgsForCall = append(fake.newResourceScannerArgsForCall, struct {
		pipeline dbng.Pipeline
	}{pipeline})
	fake.recordInvocation("NewResourceScanner", []interface{}{pipeline})
	fake.newResourceScannerMutex.Unlock()
	if fake.NewResourceScannerStub != nil {
		return fake.NewResourceScannerStub(pipeline)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.newResourceScannerReturns.result1
}

func (fake *FakeScannerFactory) NewResourceScannerCallCount() int {
	fake.newResourceScannerMutex.RLock()
	defer fake.newResourceScannerMutex.RUnlock()
	return len(fake.newResourceScannerArgsForCall)
}

func (fake *FakeScannerFactory) NewResourceScannerArgsForCall(i int) dbng.Pipeline {
	fake.newResourceScannerMutex.RLock()
	defer fake.newResourceScannerMutex.RUnlock()
	return fake.newResourceScannerArgsForCall[i].pipeline
}

func (fake *FakeScannerFactory) NewResourceScannerReturns(result1 radar.Scanner) {
	fake.NewResourceScannerStub = nil
	fake.newResourceScannerReturns = struct {
		result1 radar.Scanner
	}{result1}
}

func (fake *FakeScannerFactory) NewResourceScannerReturnsOnCall(i int, result1 radar.Scanner) {
	fake.NewResourceScannerStub = nil
	if fake.newResourceScannerReturnsOnCall == nil {
		fake.newResourceScannerReturnsOnCall = make(map[int]struct {
			result1 radar.Scanner
		})
	}
	fake.newResourceScannerReturnsOnCall[i] = struct {
		result1 radar.Scanner
	}{result1}
}

func (fake *FakeScannerFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.newResourceScannerMutex.RLock()
	defer fake.newResourceScannerMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeScannerFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ resourceserver.ScannerFactory = new(FakeScannerFactory)
