#!/bin/bash

set -e -u

cd $(dirname $0)/..

ROOT=$(pwd)

DEVDIR=/tmp/concourse-dev
KEYSDIR=$DEVDIR/keys

go install ./atc/cmd/atc

pg_port=${POSTGRES_PORT:-6543}

until createdb -U postgres -p ${pg_port} atc 2>&1 | grep 'already exists' >/dev/null; do
  echo creating database ...
  sleep 1
done

atc run \
  --log-level debug \
  --external-url "http://localhost:8080" \
  --session-signing-key $KEYSDIR/web/session_signing_key \
  --postgres-user "postgres" \
  --postgres-database "atc" \
  --postgres-port "${pg_port}" \
  --postgres-sslmode "disable" \
  --add-local-user 'user:user' \
  --add-local-user 'test:test' \
  --add-local-user 'test2:test2' \
  --add-local-user 'test3:test3' \
  --add-local-user 'test4:test4' \
  --main-team-local-user "user" \
  --main-team-local-user "test" \
  --main-team-local-user "test3" \
  --main-team-local-user "test4" \
  "$@"
