#!/bin/bash

set -e -u

ROOT=$(cd $(dirname $0)/.. && pwd)

DEVDIR=/tmp/concourse-dev
KEYSDIR=$DEVDIR/keys

export GOPATH=$ROOT
export PATH=$ROOT/bin:$PATH

go install github.com/concourse/atc/cmd/atc

external_ip="$(ip route get 8.8.8.8 | grep src | head -1 | sed 's/.*src \([^ ]\+\).*/\1/')"

atc \
  --development-mode \
  --external-url "http://${external_ip}:8080" \
  --session-signing-key $KEYSDIR/web/session_signing_key
