#!/bin/bash

set -e -u

cd $(dirname $0)/..

ROOT=$(pwd)
KEYSDIR=$ROOT/dev/keys

mkdir -p $KEYSDIR
cd $KEYSDIR

pwd
mkdir -p web worker

function keygen() {
  [ -f $1 ] || ssh-keygen -t rsa -f $1 -N ''
}

keygen ./web/tsa_host_key
keygen ./web/session_signing_key
keygen ./worker/worker_key

cp ./worker/worker_key.pub ./web/authorized_worker_keys
cp ./web/tsa_host_key.pub ./worker
