#!/bin/bash

set -e -u

cd $(dirname $0)/..

ROOT=$(pwd)

DEVDIR=/tmp/concourse-dev
DBDIR=$DEVDIR/db

[ -d $DBDIR ] || initdb -U postgres -D $DBDIR -E UTF8 --no-local

exec postgres -D $DBDIR -h 127.0.0.1 -p ${POSTGRES_PORT:-6543} "$@"
