#!/bin/bash
set -e -u

ROOT=$(cd $(dirname $0)/.. && pwd)

DEVDIR=/tmp/concourse-dev
DBDIR=$DEVDIR/db
docker_postgres="${DOCKER_POSTGRES:-concourse-db}"

if [ $(docker ps --filter name=${docker_postgres} | grep -c ${docker_postgres}) = 0 ] ; then
  exec docker run --rm --name ${docker_postgres} -p 127.0.0.1:${POSTGRES_PORT:-6543}:5432 -v $(pwd)/postgresql.conf:/etc/postgresql/postgresql.conf -d postgres:alpine -c 'config_file=/etc/postgresql/postgresql.conf' "$@"
else
  echo "Docker container ${docker_postgres} is already up and running"
fi
