#!/bin/bash

set -e -u

if [ "$#" -gt 3 ]; then
  echo "usage: $1 <user/repo> <matcher> <asset name>"
  exit 1
fi

repo=$1
asset_matcher=$2
asset_name=$3

cd $(dirname $0)/..

ROOT=$(pwd)
ASSETSDIR=$ROOT/dev/image

asset=$ASSETSDIR/$asset_name
if [ -e $asset ]; then
  echo "gdn already fetched; skipping"
  exit 0
fi

url=$(curl --silent https://api.github.com/repos/$repo/releases/latest | jq -r '.assets[] | select(.name | test($regex)) | .browser_download_url' --arg regex "$asset_matcher")
if [ -z "$url" ]; then
  echo "could not get download URL for $asset_name"
  exit 1
fi

mkdir -p $(dirname $asset)
curl -L $url -o $asset
chmod +x $asset
