#!/bin/bash

set -e -u

cd $(dirname $0)/..
source dev/ui.sh

[ "$#" -lt 3 ] && abort "usage: $1 <user/repo> <asset regex> <destination>"

repo=$1
regex=$2
destination=$3

if [ -e $destination ]; then
  by "$destination already fetched; skipping"
  exit 0
fi

asset_url=$(
  curl --silent https://api.github.com/repos/$repo/releases/latest | \
    jq -r '.assets[] | select(.name | test($regex)) | .browser_download_url' \
      --arg regex "$regex"
)
if [ -z "$asset_url" ]; then
  abort "could not get download URL for $repo latest release (asset: $regex)"
fi

by "fetching $destination"
mkdir -p $(dirname $destination)
curl -L $asset_url -o $destination
chmod +x $destination
