#!/bin/bash

set -e -u

cd $(dirname $0)/..
source dev/ui.sh

[ "$#" -lt 1 ] && abort "usage: $0 <destination>"

destination=$1

for r in registry-image git s3 mirror; do
  resdir=$destination/$r

  if [ -e "$resdir/resource_metadata.json" ]; then
    progress "$r already fetched; skipping"
    continue
  fi

  url=$(curl --silent https://api.github.com/repos/concourse/${r}-resource/releases/latest | jq -r '.assets[0].browser_download_url')
  [ -z "$url" ] && abort "could not get download URL for $r resource"

  by "fetching $r resource..."

  mkdir -p $resdir
  curl -L $url | tar -C $resdir -zxf -
done
