#!/bin/bash

set -e -u

ROOT=$(cd $(dirname $0)/.. && pwd)

DEVDIR=/tmp/concourse-dev
KEYSDIR=$DEVDIR/keys

WORKDIR=$DEVDIR/workdir

sudo concourse worker \
  --work-dir $WORKDIR \
  --tsa-host 127.0.0.1:2222 \
  --tsa-public-key $KEYSDIR/web/tsa_host_key.pub \
  --tsa-worker-private-key $KEYSDIR/worker/worker_key

