#!/bin/bash

set -e -u

cd $(dirname $0)/..

ROOT=$(pwd)
ASSETSDIR=$ROOT/dev/image

./dev/create-keys
./dev/fetch-release-binary cloudfoundry/garden-runc-release gdn gdn
./dev/fetch-release-binary Yelp/dumb-init 'dumb-init_.*_amd64$' dumb-init
./dev/fetch-resources

GOOS=linux GOARCH=amd64 packr build \
  -o $ASSETSDIR/concourse \
  github.com/concourse/concourse/bin/cmd/concourse
