#!/bin/bash

set -e -u

cd $(dirname $0)/..

ROOT=$(pwd)

DEVDIR=/tmp/concourse-dev
KEYSDIR=$DEVDIR/keys

external_ip="$($ROOT/dev/util/external-ip)"

exec docker run --rm --privileged -v $KEYSDIR/worker:/concourse-keys \
  concourse/concourse-rc worker --tsa-host "$external_ip:2222" --ephemeral "$@"
