#!/bin/bash

set -e -u

ROOT=$(cd $(dirname $0)/.. && pwd)

DEVDIR=/tmp/concourse-dev
KEYSDIR=$DEVDIR/keys

external_ip="$($ROOT/dev/util/external-ip)"

docker="sudo docker"
if [ -n "$DOCKER_HOST" ]; then
  # assume docker-machine or remote docker w/ auth
  docker="docker"
fi

$docker run --rm --privileged -v $KEYSDIR/worker:/concourse-keys \
  concourse/concourse worker --tsa-host "$external_ip"
