// Code generated by counterfeiter. DO NOT EDIT.
package uidgidfakes

import (
	"os/exec"
	"sync"

	lager "code.cloudfoundry.org/lager/v3"
	"github.com/concourse/concourse/worker/baggageclaim/uidgid"
)

type FakeNamespacer struct {
	NamespaceCommandStub        func(*exec.Cmd)
	namespaceCommandMutex       sync.RWMutex
	namespaceCommandArgsForCall []struct {
		arg1 *exec.Cmd
	}
	NamespacePathStub        func(lager.Logger, string) error
	namespacePathMutex       sync.RWMutex
	namespacePathArgsForCall []struct {
		arg1 lager.Logger
		arg2 string
	}
	namespacePathReturns struct {
		result1 error
	}
	namespacePathReturnsOnCall map[int]struct {
		result1 error
	}
	NamespacePathToUserStub        func(lager.Logger, string, int, int) error
	namespacePathToUserMutex       sync.RWMutex
	namespacePathToUserArgsForCall []struct {
		arg1 lager.Logger
		arg2 string
		arg3 int
		arg4 int
	}
	namespacePathToUserReturns struct {
		result1 error
	}
	namespacePathToUserReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeNamespacer) NamespaceCommand(arg1 *exec.Cmd) {
	fake.namespaceCommandMutex.Lock()
	fake.namespaceCommandArgsForCall = append(fake.namespaceCommandArgsForCall, struct {
		arg1 *exec.Cmd
	}{arg1})
	stub := fake.NamespaceCommandStub
	fake.recordInvocation("NamespaceCommand", []interface{}{arg1})
	fake.namespaceCommandMutex.Unlock()
	if stub != nil {
		fake.NamespaceCommandStub(arg1)
	}
}

func (fake *FakeNamespacer) NamespaceCommandCallCount() int {
	fake.namespaceCommandMutex.RLock()
	defer fake.namespaceCommandMutex.RUnlock()
	return len(fake.namespaceCommandArgsForCall)
}

func (fake *FakeNamespacer) NamespaceCommandCalls(stub func(*exec.Cmd)) {
	fake.namespaceCommandMutex.Lock()
	defer fake.namespaceCommandMutex.Unlock()
	fake.NamespaceCommandStub = stub
}

func (fake *FakeNamespacer) NamespaceCommandArgsForCall(i int) *exec.Cmd {
	fake.namespaceCommandMutex.RLock()
	defer fake.namespaceCommandMutex.RUnlock()
	argsForCall := fake.namespaceCommandArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeNamespacer) NamespacePath(arg1 lager.Logger, arg2 string) error {
	fake.namespacePathMutex.Lock()
	ret, specificReturn := fake.namespacePathReturnsOnCall[len(fake.namespacePathArgsForCall)]
	fake.namespacePathArgsForCall = append(fake.namespacePathArgsForCall, struct {
		arg1 lager.Logger
		arg2 string
	}{arg1, arg2})
	stub := fake.NamespacePathStub
	fakeReturns := fake.namespacePathReturns
	fake.recordInvocation("NamespacePath", []interface{}{arg1, arg2})
	fake.namespacePathMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeNamespacer) NamespacePathCallCount() int {
	fake.namespacePathMutex.RLock()
	defer fake.namespacePathMutex.RUnlock()
	return len(fake.namespacePathArgsForCall)
}

func (fake *FakeNamespacer) NamespacePathCalls(stub func(lager.Logger, string) error) {
	fake.namespacePathMutex.Lock()
	defer fake.namespacePathMutex.Unlock()
	fake.NamespacePathStub = stub
}

func (fake *FakeNamespacer) NamespacePathArgsForCall(i int) (lager.Logger, string) {
	fake.namespacePathMutex.RLock()
	defer fake.namespacePathMutex.RUnlock()
	argsForCall := fake.namespacePathArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeNamespacer) NamespacePathReturns(result1 error) {
	fake.namespacePathMutex.Lock()
	defer fake.namespacePathMutex.Unlock()
	fake.NamespacePathStub = nil
	fake.namespacePathReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeNamespacer) NamespacePathReturnsOnCall(i int, result1 error) {
	fake.namespacePathMutex.Lock()
	defer fake.namespacePathMutex.Unlock()
	fake.NamespacePathStub = nil
	if fake.namespacePathReturnsOnCall == nil {
		fake.namespacePathReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.namespacePathReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeNamespacer) NamespacePathToUser(arg1 lager.Logger, arg2 string, arg3 int, arg4 int) error {
	fake.namespacePathToUserMutex.Lock()
	ret, specificReturn := fake.namespacePathToUserReturnsOnCall[len(fake.namespacePathToUserArgsForCall)]
	fake.namespacePathToUserArgsForCall = append(fake.namespacePathToUserArgsForCall, struct {
		arg1 lager.Logger
		arg2 string
		arg3 int
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.NamespacePathToUserStub
	fakeReturns := fake.namespacePathToUserReturns
	fake.recordInvocation("NamespacePathToUser", []interface{}{arg1, arg2, arg3, arg4})
	fake.namespacePathToUserMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeNamespacer) NamespacePathToUserCallCount() int {
	fake.namespacePathToUserMutex.RLock()
	defer fake.namespacePathToUserMutex.RUnlock()
	return len(fake.namespacePathToUserArgsForCall)
}

func (fake *FakeNamespacer) NamespacePathToUserCalls(stub func(lager.Logger, string, int, int) error) {
	fake.namespacePathToUserMutex.Lock()
	defer fake.namespacePathToUserMutex.Unlock()
	fake.NamespacePathToUserStub = stub
}

func (fake *FakeNamespacer) NamespacePathToUserArgsForCall(i int) (lager.Logger, string, int, int) {
	fake.namespacePathToUserMutex.RLock()
	defer fake.namespacePathToUserMutex.RUnlock()
	argsForCall := fake.namespacePathToUserArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeNamespacer) NamespacePathToUserReturns(result1 error) {
	fake.namespacePathToUserMutex.Lock()
	defer fake.namespacePathToUserMutex.Unlock()
	fake.NamespacePathToUserStub = nil
	fake.namespacePathToUserReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeNamespacer) NamespacePathToUserReturnsOnCall(i int, result1 error) {
	fake.namespacePathToUserMutex.Lock()
	defer fake.namespacePathToUserMutex.Unlock()
	fake.NamespacePathToUserStub = nil
	if fake.namespacePathToUserReturnsOnCall == nil {
		fake.namespacePathToUserReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.namespacePathToUserReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeNamespacer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeNamespacer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ uidgid.Namespacer = new(FakeNamespacer)
