services:
  web:
    environment:
      CONCOURSE_EXTERNAL_URL: https://localhost:443
      CONCOURSE_TLS_BIND_PORT: 8443
      CONCOURSE_TLS_CERT: /src/hack/mtls_certs/concourse/web.cert.pem
      CONCOURSE_TLS_CA_CERT: /src/hack/mtls_certs/concourse/ca-chain.cert.pem
      CONCOURSE_TLS_KEY: /src/hack/mtls_certs/concourse/web.key.pem

  nginx:
    image: nginx:latest
    depends_on: [web]
    volumes:
    - ./hack/nginx/conf.d:/etc/nginx/conf.d
    - ./hack/mtls_certs:/etc/nginx/mtls_certs
    ports:
      - "443:443"
