#!/bin/bash
# vim: set ft=sh

set -e -x

export PATH=/usr/lib/postgresql/9.3/bin:$PATH

export GOPATH=$PWD/concourse
export PATH=$GOPATH/bin:$PATH

go install github.com/onsi/ginkgo/ginkgo

cd ${GOPATH}/src/github.com/concourse/atc
ginkgo -r -p "$@"

mkdir ~/npm
npm config set prefix ~/npm
export PATH="$PATH:$HOME/npm/bin"

cd web/javascript
npm install
npm install -g gulp
gulp jasmine-cli
