#!/bin/bash
# vim: set ft=sh

set -e -x

pushd concourse/src/github.com/concourse/atc/web
  npm install

  export PATH=$(npm bin):$PATH

  gulp jasmine-cli

  pushd elm
    elm-package install --yes

    # LANG is needs to be set explicitly because of this Elm bug:
    #   https://github.com/elm-lang/elm-make/issues/33
    LANG=en_US.UTF-8 elm-test TestRunner.elm
  popd
popd
