#!/bin/bash
# vim: set ft=sh

set -e -x

export PATH=/usr/lib/postgresql/9.3/bin:$PATH

export GOPATH=$PWD/concourse
export PATH=$GOPATH/bin:$PATH

pushd ${GOPATH}/src/github.com/concourse/atc
  go install github.com/onsi/ginkgo/ginkgo
  ginkgo -r -p -race "$@"
popd
