#!/bin/bash
# vim: set ft=sh

set -e -x

pushd concourse/src/github.com/concourse/atc/web
  # https://twitter.com/gavinjoyce/status/691773956144119808
  npm set progress=false
  npm install --silent

  export PATH=$(npm bin):$PATH

  gulp jasmine-cli

  pushd elm
    elm-package install --yes
    elm-test TestRunner.elm
  popd
popd
