#!/bin/bash
# vim: set ft=sh

set -e -x

export GOPATH=$PWD/concourse
export PATH=$GOPATH/bin:$PATH

pushd ${GOPATH}/src/github.com/concourse/atc
  go install github.com/onsi/ginkgo/ginkgo
  FORCE_SELENIUM=true xvfb-run ginkgo -r -p -race "$@"
popd
