#!/bin/bash
# vim: set ft=sh

set -e -x

export GOPATH=$PWD/concourse
export PATH=$GOPATH/bin:$PATH

mkdir /tmp/concourse-pg-runner
if ! mount -t tmpfs none /tmp/concourse-pg-runner; then
  echo 'failed to mount tmpfs for pg. this is OK, db suite will just be slow'
fi

pushd ${GOPATH}/src/github.com/concourse/atc
  go install github.com/onsi/ginkgo/ginkgo
  ginkgo -r -p -race "$@"
popd
