#!/bin/bash

set -e

NOTES=$PWD/release-notes

version=$(cat version/version)

echo v${version} > $NOTES/release-name

cat > $NOTES/notes.md <<EOF
See [v${version} release notes](http://concourse.ci/release-notes.html#v${version})
EOF
