#!/bin/bash

set -e

function abort() {
  echo "$@" >&2
  exit 1
}

[ -n "$VERSION_FILE" ] || abort "must specify \$VERSION_FILE"
[ -f "$VERSION_FILE" ] || abort "'$VERSION_FILE' does not exist"

version=$(cat ${VERSION_FILE})
site_id=${SITE_ID}

cd docs/docs/

if [ -n "$ANALYTICS_ID" ]; then
  raco scribble ++arg ${version} ++arg "$ANALYTICS_ID" --htmls concourse.scrbl
else
  raco scribble ++arg ${version} --htmls concourse.scrbl
fi
