#!/bin/bash
# vim: set ft=sh

set -e -x

output_dir=$PWD/btrfs-tools

apt-get update
apt-get -y install liblzo2-dev libblkid-dev e2fslibs-dev pkg-config libz-dev curl

cd /tmp
curl https://www.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v4.4.tar.gz | tar zxf -

cd btrfs-progs-v4.4

LDFLAGS=-static ./configure --disable-documentation

make

tar zcf $output_dir/btrfs-tools.tar.gz btrfs mkfs.btrfs
