#!/bin/bash

set -e

version=$(cat final-release/version)

echo v${version} > release-name

cat > notes.md <<EOF
See [v${version} release notes](http://concourse.ci/release-notes.html#v${version})
EOF
