#!/bin/sh

set -e -x

export GOPATH=$PWD/concourse
export PATH=$PWD/bin:$PATH

export DISTDIR=$PWD/dist
mkdir -p $DISTDIR/artifacts

echo "v$(cat version/number)" > $DISTDIR/release-name

cd $GOPATH/src/github.com/concourse/gate

GOOS=darwin GOARCH=amd64 go build \
  -a -tags netgo -installsuffix netgo \
  -o $DISTDIR/artifacts/gate_darwin_amd64 ./cmd/gate

GOOS=linux GOARCH=amd64 go build \
  -a -tags netgo -installsuffix netgo \
  -o $DISTDIR/artifacts/gate_linux_amd64 ./cmd/gate

GOOS=windows GOARCH=amd64 go build \
  -a -tags netgo -installsuffix netgo \
  -o $DISTDIR/artifacts/gate.exe ./cmd/gate
