#!/bin/bash
# vim: set ft=sh

set -e -x

pushd resource-repo
  COMMIT_SHA=$(git rev-parse --short=7 HEAD)
popd

if [ -z "$RESOURCE_NAME" ]; then
  echo "must specify \$RESOURCE_NAME" >&2
  exit 1
fi

gzip -c resource-image/rootfs.tar > ${RESOURCE_NAME}.tar.gz

git clone concourse bumped-concourse

set +x
echo "$BOSH_PRIVATE_CONFIG" > bumped-concourse/config/private.yml
set -x

cd bumped-concourse/

# work-around Go BOSH CLI trying to rename blobs downloaded into ~/.root/tmp
# into release dir, which is invalid cross-device link
export HOME=$PWD

git config --global user.email "ci@localhost"
git config --global user.name "CI Bot"

bosh blobs --column="path"  | grep "resources/${RESOURCE_NAME}" | xargs bosh remove-blob

bosh -n add-blob ../${RESOURCE_NAME}.tar.gz resources/${RESOURCE_NAME}-${COMMIT_SHA}.tar.gz
bosh -n upload-blobs

if ! git diff-index --quiet HEAD; then
  git add -A
  git commit -m "update ${RESOURCE_NAME} blob"
fi
