#!/bin/bash
# vim: set ft=sh

set -e -x

if [ -z "$RESOURCE_NAME" ]; then
  echo "must specify \$RESOURCE_NAME" >&2
  exit 1
fi

git config --global user.email "ci@localhost"
git config --global user.name "CI Bot"

cp deployments/ci/config/private.yml concourse/config/private.yml

gzip -c resource-image/rootfs.tar > ${RESOURCE_NAME}.tar.gz

cd concourse/

bosh -n add blob ../${RESOURCE_NAME}.tar.gz resources
bosh -n upload blobs

git add -A
git commit -m "update ${RESOURCE_NAME} blob"
