#!/bin/bash
set -e

CHART=$PWD/helm-chart

unnecessary="CONCOURSE_VERSION"
expected=
for sc in web worker; do
  expected+="$(concourse $sc --help 2>&1 | grep -o '\[\$CONCOURSE_.*\]' | tr -d \[\]\$ | grep -v "$unnecessary")\n"
done
actual="$(grep -REhv '\s+#\s+' $CHART | grep -Eoh 'CONCOURSE_([A-Z_])+')"
echo These parameters need to be removed from the Helm chart:
to_remove=$(comm -23 <(echo "$actual" | sort | uniq) <(echo -e "$expected" | sort | uniq) | paste -sd, -)
echo "$to_remove"
echo These parameters need to be added to the Helm chart:
to_add=$(comm -13 <(echo "$actual" | sort | uniq) <(echo -e "$expected" | sort | uniq) | paste -sd, -)
echo "$to_add"
[ -z "$to_remove" ] && [ -z "$to_add" ]
