#!/bin/bash
set -e

CHART=$PWD/helm-chart
concourse_ignore_list="CONCOURSE_VERSION|CREDHUB"
k8s_ignore_list="LIVENESS_PROBE_FATAL_ERRORS|POD_IP"

expected=
for sc in web worker; do
  expected+="$(concourse $sc --help 2>&1 | grep -o '\[\$.*\]' | tr -d \[\]\$ | egrep -v "$concourse_ignore_list")\n"
done
actual="$(grep -REhv '\s+#\s+' $CHART | grep -Eoh 'name: (([A-Z_])+|http_proxy|https_proxy|no_proxy)' | sed -e "s/^name: //" | egrep -v "$k8s_ignore_list")"
echo These parameters need to be removed from the Helm chart:
to_remove=$(comm -23 <(echo "$actual" | sort | uniq) <(echo -e "$expected" | sort | uniq) | paste -sd, -)
echo "$to_remove"
echo These parameters need to be added to the Helm chart:
to_add=$(comm -13 <(echo "$actual" | sort | uniq) <(echo -e "$expected" | sort | uniq) | paste -sd, -)
echo "$to_add"
[ -z "$to_remove" ] && [ -z "$to_add" ]
