#!/bin/bash
# vim: set ft=sh

set -e

OUTPUT="$PWD/bosh-rc"
VERSION="$(cat version/version)"
FINAL_VERSION="$(cat final-version/version)"

pushd concourse/
  echo "$FINAL_VERSION" > src/version/VERSION

  bosh -n create-release --tarball --name concourse --version "$VERSION"
  mv dev_releases/concourse/concourse-*.tgz "$OUTPUT"
popd
