#!/bin/bash
# vim: set ft=sh

set -e

OUTPUT="$PWD/bosh-rc"
VERSION="$(cat version/version)"
FINAL_VERSION="$(cat final-version/version)"

# work-around Go BOSH CLI trying to rename blobs downloaded into ~/.root/tmp
# into release dir, which is invalid cross-device link
export HOME=$PWD

pushd concourse/
  echo "$FINAL_VERSION" > src/version/VERSION

  bosh -n create-release --tarball --name concourse --version "$VERSION"
  mv dev_releases/concourse/concourse-*.tgz "$OUTPUT"
popd
