#!/bin/bash

set -e

eval $(ssh-agent)
ssh-add <(echo "$BOSH_KEY")

VERSION="$(echo windows-worker/version)"

bosh manifest > prod.yml

sed -i -e 's/${VERSION}/latest/g' prod.yml

bosh deploy prod.yml
