#!/bin/bash
# vim: set ft=sh

set -e -x

source ./deployments/ci/bosh_environment

VERSION=$(cat ./version/number)
if [ -z "$VERSION" ]; then
  echo "missing version number"
  exit 1
fi

set +x
  spiff diff --separator $'\f' \
    concourse/manifests/aws-vpc.yml \
    deployments/ci/deployments/concourse.yml | \
    awk -v RS='\f' '!/pipeline|REPLACE|basic_auth|publicly_viewable|blackbox|consul-agent/' |
    tee /tmp/manifest-diff

  if [ -s /tmp/manifest-diff ]; then
    echo $'\x1b[31m!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\x1b[0m'
    echo $'\x1b[31m!! WARNING: VPC EXEMPLARY MANIFEST CHANGES DETECTED !!\x1b[0m'
    echo $'\x1b[31m!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\x1b[0m'
  fi
set -x

cp deployments/ci/config/private.yml concourse/config/private.yml

bosh target ${BOSH_TARGET}

bosh deployment deployments/ci/deployments/concourse.yml

bosh -n upload stemcell bosh-stemcell/*.tgz --skip-if-exists

bosh -n upload release garden-linux-release/*.tgz --skip-if-exists

cd concourse/

git config --global user.email "ci@localhost"
git config --global user.name "CI Bot"

git merge --no-edit master

bosh -n create release --final --version "$VERSION"
bosh -n upload release --skip-if-exists

bosh -n deploy
