#!/bin/bash
# vim: set ft=sh

set -e -x

source ./deployments/ci/bosh_environment

VERSION=$(cat ./version/number)
if [ -z "$VERSION" ]; then
  echo "missing version number"
  exit 1
fi

set +x
  spiff diff --separator $'\f' \
    concourse/manifests/aws-vpc.yml \
    deployments/ci/deployments/concourse.yml | \
    awk -v RS='\f' '!/pipeline|REPLACE|basic_auth|publicly_viewable|blackbox|consul-agent|password|username|authorized_keys|host_key|host_public_key|instances|instance_type|10.0.16.10|templates/' |
    tee /tmp/manifest-diff

  if [ -s /tmp/manifest-diff ]; then
    echo $'\x1b[31m!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\x1b[0m'
    echo $'\x1b[31m!! WARNING: VPC EXEMPLARY MANIFEST CHANGES DETECTED !!\x1b[0m'
    echo $'\x1b[31m!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\x1b[0m'
  fi
set -x

cp deployments/ci/config/private.yml concourse/config/private.yml

cd concourse/

git config --global user.email "ci@localhost"
git config --global user.name "CI Bot"

git merge --no-edit master

bosh -n create release --with-tarball --version "$VERSION"
