#!/bin/bash
# vim: set ft=sh

set -e -x

EXPORTED_LOGS=$PWD/exported-logs

bosh env $(cat bosh-lites/metadata | tr '.' '-').sslip.io --ca-cert bosh-lite/ca/certs/ca.crt

bosh -d concourse-testflight logs concourse/0 --only '*.log,**/*.log'

mv concourse*.tgz $EXPORTED_LOGS
