#!/bin/bash

set -e -u -x

exported_release=$PWD/exported-release

RELEASE_VERSION=$(cat release/version)
STEMCELL_VERSION=$(cat stemcell/version)

bosh export-release \
  --dir ${exported_release} \
  ${RELEASE_NAME}/${RELEASE_VERSION} \
  ${STEMCELL_NAME}/${STEMCELL_VERSION}

mv ${exported_release}/*.tgz ${exported_release}/${RELEASE_NAME}-${RELEASE_VERSION}-${STEMCELL_VERSION}.tgz
