#!/bin/bash
# vim: set ft=sh

set -e -x

EXPORTED_LOGS=$PWD/exported-logs

bosh target $(cat bosh-lites/metadata)

director_uuid=$(bosh status --uuid)

cat deployments/lite/ci/manifests/no_auth_deployment.yml | sed "s/director_uuid: ~/director_uuid: $director_uuid/g" > deployment.yml

bosh -d deployment.yml logs concourse 0 --only '*.log,**/*.log'

cat deployments/lite/ci/manifests/basic_auth_deployment.yml | sed "s/director_uuid: ~/director_uuid: $director_uuid/g" > deployment.yml

bosh -d deployment.yml logs concourse 0 --only '*.log,**/*.log'

mv concourse*.tgz $EXPORTED_LOGS
