#!/bin/bash
# vim: set ft=sh

set -e -x

#bosh target $(cat bosh-lites/metadata)
bosh target 10.0.22.106

director_uuid=$(bosh status --uuid)

cat concourse/src/github.com/concourse/testflight/deployment.yml | sed "s/director_uuid: ~/director_uuid: $director_uuid/g" > deployment.yml

bosh -d deployment.yml logs concourse 0 

