#!/bin/bash
# vim: set ft=sh

set -e

source ./deployments/ci/bosh_environment

set -x

VERSION=$(cat ./version/number)
if [ -z "$VERSION" ]; then
  echo "missing version number"
  exit 1
fi

cp deployments/ci/config/private.yml concourse/config/private.yml

cd concourse/

git config --global user.email "ci@localhost"
git config --global user.name "CI Bot"

git merge --no-edit master

bosh -n finalize release --version "$VERSION" candidate-release/concourse-*.tgz

git add -A
git commit -m "release v${VERSION}"
