#!/bin/bash
# vim: set ft=sh

set -e

source ./deployments/ci/bosh_environment

set -x

ROOT_DIR=$PWD
CANDIDATE_DIR=$PWD/candidate-release

VERSION=$(cat ./version/number)
if [ -z "$VERSION" ]; then
  echo "missing version number"
  exit 1
fi

cp deployments/ci/config/private.yml concourse/config/private.yml

cd concourse/

git config --global user.email "ci@localhost"
git config --global user.name "CI Bot"

git merge --no-edit master

RELEASE_YML=$PWD/releases/concourse/concourse-${VERSION}.yml
RELEASE_TGZ=$PWD/releases/concourse/concourse-${VERSION}.tgz

if [ -e ${RELEASE_YML} ]; then
  echo "release already created; making tarball..."
  bosh -n create release --with-tarball ${RELEASE_YML}
else
  echo "finalizing release"
  bosh -n finalize release --version "$VERSION" ${CANDIDATE_DIR}/concourse-*.tgz
  git add -A
  git commit -m "release v${VERSION}"
fi

mv ${RELEASE_TGZ} ${ROOT_DIR}
