#!/bin/bash
# vim: set ft=sh

set -e -x

export GOPATH=$PWD/concourse
export PATH=$GOPATH/bin:/usr/local/bin:$PATH
export HOME=$PWD

FINAL_VERSION="$(cat final-version/version)"

cd ${GOPATH}/src/github.com/concourse/fly

GOARCH=amd64 CGO_ENABLED=0 \
    go build \
    -ldflags "-X github.com/concourse/fly/version.Version=${FINAL_VERSION}" \
    -o ${HOME}/${platform}-binary/fly_${platform}_amd64 \
    github.com/concourse/fly
