#!/bin/bash

set -ex

FROM_COMMIT=$(cat ./from-commit/ref)
TO_COMMIT=$(cat ./to-commit/ref)

pushd concourse
  issues=$(git log $FROM_COMMIT...$TO_COMMIT --grep=concourse/concourse | grep concourse/concourse)
popd

echo $HEADING > ./message/text

for issue in $issues
do
    echo "- https://github.com/${issue}" | sed 's/#/\/issues\//' >> ./message/text
done
