#!/bin/sh

set -e -x

export PATH=$GOPATH/bin:$PATH

cd concourse-master

git checkout develop

git config --global user.email "ci@localhost"
git config --global user.name "CI Bot"

git merge --no-edit master
