#!/bin/bash
# vim: set ft=sh

set -e

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

export GOPATH=${PWD}/concourse
export PATH=${PWD}/concourse/bin:$PATH

go install github.com/onsi/ginkgo/ginkgo

export BOSH_USER=admin
export BOSH_PASSWORD=admin

bosh target ${BOSH_LITE_IP}

cd concourse/src/github.com/concourse/testflight/
ginkgo -v -r -race "$@"
