#!/bin/bash
# vim: set ft=sh

set -e

readonly ATC_URL=${ATC_URL:-http://$(cat ./endpoint-info/instance-ip):8080}

export GOPATH=${PWD}/concourse
export PATH=${PWD}/concourse/bin:$PATH

go install github.com/onsi/ginkgo/ginkgo

cd concourse/src/github.com/concourse/testflight/
ginkgo -r -nodes=3 -race "$@"
