#!/bin/bash
# vim: set ft=sh

set -e -x

bosh target $(cat bosh-lites/metadata)

bosh upload stemcell --skip-if-exists lite-stemcell/*.tgz
bosh upload release --skip-if-exists garden-linux-release/*.tgz
bosh upload release --skip-if-exists candidate-release/*.tgz
