#!/bin/bash
# vim: set ft=sh

set -e -x

bosh target $(cat bosh-lites/metadata)

bosh upload stemcell lite-stemcell/*.tgz
bosh upload release garden-linux-release/*.tgz
bosh upload release candidate-release/*.tgz
