#!/bin/bash
# vim: set ft=sh

set -e

export GOPATH=${PWD}/concourse
export PATH=${PWD}/concourse/bin:$PATH

export GEM_HOME=${PWD}/gems
export BUNDLE_PATH=${PWD}/gems

export ATC_URL=http://$(cat endpoint-info/instance_ip):8080

go install github.com/concourse/fly

export DISPLAY=:99.0
Xvfb $DISPLAY -ac +extension RANDR &
trap "kill $!" EXIT

cd concourse/src/github.com/concourse/web/acceptance/
bundle
bundle exec rspec --tag ~perf
