#!/bin/bash
# vim: set ft=sh

set -e

export ATC_URL=$(cat endpoint-info/instance_ip)

install fly-rc/fly_linux_amd64 /usr/local/bin/fly

cd concourse/src/github.com/concourse/web/wats/

yarn install --no-progress
yarn test -v --color
