#!/bin/bash
# vim: set ft=sh

set -e

export GOPATH=${PWD}/concourse
export PATH=${PWD}/concourse/bin:$PATH

go install github.com/concourse/fly

cd concourse/src/github.com/concourse/atc/web/acceptance/
bundle
bundle exec rspec
