#!/bin/bash
# vim: set ft=sh

set -e -x

export GOPATH=$PWD/concourse
export PATH=$GOPATH/bin:$PATH

go install github.com/onsi/ginkgo/ginkgo

cd ${GOPATH}/src/github.com/concourse/web

ginkgo -r -race -p --failOnPending --randomizeAllSpecs "$@"
