services:
  db:
    # we need to persist the db between restarts
    environment:
      PGDATA: /var/lib/postgresql/concourse/data
    volumes:
      - postgresData:/var/lib/postgresql/concourse/data

  web:
    environment:
      # faketime doesn't work with go binaries. The code relies on sql to
      # determine the current time anyways so we can workaround this by simply
      # having the pipeline pauser run more frequently
      CONCOURSE_PAUSE_PIPELINES_AFTER: 3

volumes:
  postgresData:
