---
name: concourse

# replace with bosh status --uuid
director_uuid: REPLACE_WITH_UUID

# pick a sane db name and password
atc_db_name: &atc-db-name atc
atc_db_role: &atc-db-role
  name: atc
  password: REPLACE_WITH_DB_PASSWORD

networks:
  - name: concourse
    type: manual
    subnets:
      - range: 10.0.16.0/20
        reserved: [10.0.16.2 - 10.0.16.9]
        static:
          - &discovery_static_ip 10.0.16.10
        dns: [168.63.129.16]
        gateway: 10.0.16.1
        cloud_properties:
          virtual_network_name: REPLACE_WITH_VNET
          subnet_name: REPLACE_WITH_SUBNETNAME

releases:
  - name: concourse
    version: latest
  - name: garden-linux
    version: latest

jobs:
  - name: discovery
    instances: 1
    resource_pool: discovery
    persistent_disk: 1024
    templates:
      - {release: concourse, name: consul-agent}
    networks:
      - name: concourse
        static_ips: [*discovery_static_ip]
    properties:
      consul:
        agent:
          mode: server

  - name: web
    instances: 1
    resource_pool: web
    templates:
      - {release: concourse, name: consul-agent}
      - {release: concourse, name: tsa}
      - {release: concourse, name: atc}
    networks: [{name: concourse}]
    properties:
      atc:
        basic_auth_username: REPLACE_WITH_ATC_USERNAME
        basic_auth_password: REPLACE_WITH_ATC_PASSWORD
        external_url: REPLACE_WITH_ATC_EXTERNAL_URL
        postgresql:
          database: *atc-db-name
          role: *atc-db-role

      consul:
        agent:
          servers: {lan: [*discovery_static_ip]}

  - name: db
    instances: 1
    resource_pool: databases
    persistent_disk_pool: database
    templates:
      - {release: concourse, name: consul-agent}
      - {release: concourse, name: postgresql}
    networks: [{name: concourse}]
    properties:
      postgresql:
        databases: [{name: *atc-db-name}]
        roles: [*atc-db-role]

      consul:
        agent:
          servers: {lan: [*discovery_static_ip]}

  - name: worker
    instances: 1
    resource_pool: workers
    templates:
      - {release: concourse, name: consul-agent}
      - {release: concourse, name: groundcrew}
      - {release: concourse, name: baggageclaim}
      - {release: garden-linux, name: garden}
    networks: [{name: concourse}]
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777

      consul:
        agent:
          servers: {lan: [*discovery_static_ip]}

disk_pools:
  - name: database
    disk_size: 10240

resource_pools:
  - name: web
    network: concourse
    stemcell: &stemcell
      name: bosh-azure-hyperv-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      instance_type: Standard_D1

  - name: discovery
    network: concourse
    stemcell: *stemcell
    cloud_properties:
      instance_type: Standard_D1

  - name: databases
    network: concourse
    stemcell: *stemcell
    cloud_properties:
      instance_type: Standard_D1

  - name: workers
    network: concourse
    stemcell: *stemcell
    cloud_properties:
      instance_type: Standard_D1

compilation:
  workers: 3
  network: concourse
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: Standard_D1

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
