name: 📥 Add Work Item
description: Create an issue for concrete work that anyone in the community can work on.

body:
  - type: markdown
    attributes:
      value: |
        This issue should be for any feature work that needs to be tracked.
        It's the final place after having discussed the issue in a [Discussion
        post](https://github.com/orgs/concourse/discussions),
        [RFC](https://github.com/concourse/rfcs/), or Discord.

        Creating this issue does not mean it will be prioritized or worked on
        by the Concourse maintainers. Anyone in the community is free to work
        on this issue, including you, the person submitting this issue.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A brief summary of the task to be completed.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Links to any related discussions, issues, or RFC
      placeholder: |
        Discussion Post(s):
        Related Issue(s):
        RFC:
