#!/bin/bash

set -e -u

cd $(dirname $0)/..

container_name=""
case $1 in
web)
  container_name="concourse_web_1"
  ;;

worker)
  container_name="concourse_worker_1"
  ;;

*)
  echo "Usage: debug (web|worker)"
  exit 1
  ;;
esac

debug_pid=$(docker exec $container_name pidof concourse)

docker build --tag dlv ./hack/dlv

docker run -p 2345:2345 \
  --interactive \
  --pid=container:$container_name \
  --privileged \
  --rm \
  --tty \
  dlv \
  attach $debug_pid \
  --headless=true \
  --listen=:2345 \
  --api-version=2 \
  --log
