#!/bin/bash

# k8s-deploy - deploys Concourse against a running k8s cluster making use
#              of a local Helm chat indicated by the first positional
#              argument supplied to the script.

set -o errexit

readonly HELM_RELEASE=${HELM_RELEASE:-"local"}
readonly IMAGE_NAME=${IMAGE_NAME:-"concourse/concourse"}
readonly IMAGE_DIGEST=${IMAGE_DIGEST:-""}
readonly IMAGE_TAG=${IMAGE_TAG:-"local"}

if [[ -z $1 ]]; then
	echo "Usage: $0 <charts_dir>"
	exit 1
fi

charts_dir=$1

echo "Starting Concourse Helm deploy

HELM_RELEASE  $HELM_RELEASE
IMAGE_NAME    $IMAGE_NAME
IMAGE_TAG     $IMAGE_TAG
IMAGE_DIGEST  $IMAGE_DIGEST
"

helm dependency update $charts_dir

helm upgrade \
	-f $charts_dir/values.yaml \
	--install \
	--force \
	--set=image=$IMAGE_NAME \
	--set=imageDigest=$IMAGE_DIGEST \
	--set=imageTag=$IMAGE_TAG \
	--set=worker.replicas=1 \
	--set=prometheus.enabled=true \
	--set=concourse.web.prometheus.enabled=true \
	--set=concourse.web.kubernetes.keepNamespaces=false \
	--set=concourse.worker.ephemeral=true \
	--set=concourse.worker.baggageclaim.driver=detect \
	$HELM_RELEASE \
	--wait \
	$charts_dir
