#!/bin/bash

set -e -u

cd $(dirname $0)/..

container_name=""
listen_cmd=""

while test $# -gt 0; do
   case "$1" in
        web)
            container_name="concourse_web_1"
            shift
            ;;
        worker)
            container_name="concourse_worker_1"
            shift
            ;;
        --listen)
            shift
            listen_cmd=" --headless=true --listen=:$1"
            shift
            ;;
        *)
          echo "Usage: trace (web|worker) [--listen port]"
          exit 1
          ;;
  esac
done



trace_pid=$(docker exec $container_name pidof concourse)

docker build --tag dlv ./hack/dlv

docker run \
  --interactive \
  --pid=container:$container_name \
  --privileged \
  --rm \
  --tty \
  dlv \
  attach $trace_pid $listen_cmd
