groups: []

resources:
- name: timestamp
  type: time
  source: {interval: 1m}

- name: infrequent-timestamp
  type: time
  source: {interval: 24h}

jobs:
- name: do-in-agg
  plan:
  - aggregate:
    - do:
      - task: agg-do-1
        config: &sleep-1
          platform: linux
          image_resource: {type: docker-image, source: {repository: busybox}}
          run: {path: sh, args: ['-xc', 'sleep 1']}
      - task: agg-do-2
        config: *sleep-1
    - task: agg-1
      config: *sleep-1
    - task: agg-2
      config: *sleep-1
    - task: agg-3
      config: *sleep-1
    ensure:
      task: agg-ensure
      config: *sleep-1

- name: agg-in-agg
  plan:
  - aggregate:
    - aggregate:
      - task: agg-do-1
        config: &sleep-1
          platform: linux
          image_resource: {type: docker-image, source: {repository: busybox}}
          run: {path: sh, args: ['-xc', 'sleep 1']}
      - task: agg-do-2
        config: *sleep-1
    - task: agg-1
      config: *sleep-1
    - task: agg-2
      config: *sleep-1
    - task: agg-3
      config: *sleep-1
    ensure:
      task: agg-ensure
      config: *sleep-1

- name: agg-in-hook
  plan:
  - task: some-task
    config: *sleep-1
    ensure:
      aggregate:
      - task: agged-ensure
        config: *sleep-1
      - task: agged-ensure
        config: *sleep-1

- name: retry-around-agg
  plan:
  - aggregate:
    - task: agg-retry-1
      attempts: 5
      config: *sleep-1
    - task: agg-1
      config: *sleep-1
    - task: agg-2
      config: *sleep-1
    - task: agg-3
      config: *sleep-1
    attempts: 50
    ensure:
      task: agg-ensure
      config: *sleep-1

- name: basic-get
  plan:
  - get: timestamp

- name: agg-get
  plan:
  - aggregate:
    - get: timestamp
    - get: infrequent-timestamp

- name: vertical-output
  plan:
  - task: numbers
    timeout: 10m
    config:
      platform: linux
      run: {path: sh, args: [-c, 'i=0; while sleep 1; do i=$(expr $i + 1); echo $i; done']}

- name: hello
  plan:
  - task: hello
    privileged: true
    config:
      platform: linux
      image_resource: {type: docker-image, source: {repository: busybox}}
      run: {path: echo, args: ['Hello world']}

- name: horizontal-output
  plan:
  - task: moar-dots
    timeout: 10m
    config:
      platform: linux
      image_resource: {type: docker-image, source: {repository: busybox}}
      run: {path: sh, args: [-c, 'while sleep 0.05; do echo -n .; done']}

- name: delayed-get
  plan:
  - task: sleep
    config:
      platform: linux
      image_resource: {type: docker-image, source: {repository: busybox}}
      run: {path: sh, args: ['-xc', 'sleep 1; sleep 1; sleep 1']}
  - get: timestamp

- name: putgets
  plan:
  - aggregate:
    - do:
      - task: agg-task
        config: *sleep-1
      ensure:
        task: do-ensure
        config: *sleep-1
    - task: agg-1
      config: *sleep-1
    - task: agg-2
      config: *sleep-1
    - task: agg-3
      config: *sleep-1
  - put: timestamp

- name: agg-in-do
  plan:
  - do:
    - task: do-2
      config: *sleep-1
    - aggregate:
      - task: do-agg-1
        config: *sleep-1
      - task: do-agg-2
        config: *sleep-1
      - task: do-agg-3
        config: *sleep-1
    - task: do-3
      config: *sleep-1
    - do:
      - task: do-do-1
        config: *sleep-1
      - task: do-do-2
        config: *sleep-1
    ensure:
      task: do-ensure
      config: *sleep-1

- name: all-the-things
  plan:
  - aggregate:
    - task: vanilla-agg-1
      config: *sleep-1
    - task: vanilla-agg-2
      config: *sleep-1
    ensure:
      task: agg-ensure
      config: *sleep-1
  - do:
    - task: vanilla-do-1
      config: *sleep-1
    - task: vanilla-do-2
      config: *sleep-1
  - do:
    - task: do-1
      config: *sleep-1
    - aggregate:
      - task: do-agg-1
        config: *sleep-1
      - task: do-agg-2
        config: *sleep-1
      ensure:
        task: agg-ensure
        config: *sleep-1
    - task: do-2
      config: *sleep-1
    ensure:
      task: do-ensure
      config: *sleep-1
  - do:
    - aggregate:
      - task: agg-first-do-agg-1
        config: *sleep-1
      - task: agg-first-do-agg-2
        config: *sleep-1
      ensure:
        task: agg-ensure
        config: *sleep-1
    - task: agg-first-do-1
      config: *sleep-1
    - task: agg-first-do-2
      config: *sleep-1
    ensure:
      task: do-ensure
      config: *sleep-1
  - aggregate:
    - task: agg-1
      config: *sleep-1
    - do:
      - task: agg-do-1
        config: *sleep-1
      - task: agg-do-2
        config: *sleep-1
    - task: agg-2
      config: *sleep-1
  - aggregate:
    - do:
      - task: do-first-agg-do-1
        config: *sleep-1
      - task: do-first-agg-do-2
        config: *sleep-1
    - task: do-first-agg-1
      config: *sleep-1
    - task: do-first-agg-2
      config: *sleep-1
  - aggregate:
    - do:
      - task: agg-with-do-only-1-do-1
        config: *sleep-1
      - task: agg-with-do-only-1-do-2
        config: *sleep-1
    - do:
      - task: agg-with-do-only-2-do-1
        config: *sleep-1
      - task: agg-with-do-only-2-do-2
        config: *sleep-1
