services:
  web:
    volumes:
    - ../hack/vault/certs:/vault-certs
    - ../hack/vault/token:/vault/token
    environment:
      CONCOURSE_VAULT_URL: https://vault:8200
      CONCOURSE_VAULT_SHARED_PATH: shared
      CONCOURSE_VAULT_CA_CERT: /vault-certs/vault-ca.crt
      CONCOURSE_VAULT_CLIENT_TOKEN_PATH: /vault/token

  vault:
    image: ${TEST_VAULT_IMAGE:-hashicorp/vault:latest}
    cap_add: [IPC_LOCK]
    ports: [8200]
    volumes:
    - ../hack/vault/certs:/vault/certs
    - ../hack/vault/config:/vault/config
    command: server
    environment:
      # for running the 'vault' CLI
      VAULT_CACERT: /vault/certs/vault-ca.crt

      # sane default for 'vault' command run by tests
      VAULT_FORMAT: json
