#!/bin/bash

set -e

NOTES=$PWD/release-notes

version=$(cat version/version)

echo v${version} > $NOTES/release-name
anchor=$(echo v${version} | tr -d .)

cat > $NOTES/notes.md <<EOF
[v${version} release notes](https://concourse-ci.org/download.html#v${anchor})
EOF
