#!/bin/bash

# check-helm-chart-parameters - verifies if there are any concourse
# parameters that are missing from the helm chart's template files
# that define environment variables.
#
# Environment variables:
#   CHART    Location of the Concourse helm chart

set -o errexit

readonly CHART=${CHART:-"$PWD/helm-chart/stable/concourse"}
readonly CONCOURSE_IGNORE_LIST="CONCOURSE_VERSION|CREDHUB"
readonly K8S_IGNORE_LIST="LIVENESS_PROBE_FATAL_ERRORS|POD_IP"

main() {
  local actual=$(get_helm_variables)
  local expected=$(get_concourse_variables)
  local diff=$(get_diff "$actual" "$expected")

  if [[ -z $diff ]]; then
    echo "All good!"
    exit 0
  fi

  echo "$diff"

  exit 1
}

get_concourse_variables() {
  for subcommand in web worker; do
    concourse $subcommand --help 2>&1 |
      grep -o '\[\$.*\]' |
      tr -d \[\]\$ |
      egrep -v "$CONCOURSE_IGNORE_LIST"
  done
}

get_helm_variables() {
  grep -REhv '\s+#\s+' $CHART |
    grep -Eoh 'name: (([A-Z_])+|http_proxy|https_proxy|no_proxy)' |
    sed -e "s/^name: //" |
    egrep -v "$K8S_IGNORE_LIST"
}

get_diff() {
  local actual=$1
  local expected=$2

  comm -23 <(echo "$expected" | sort -u) <(echo "$actual" | sort -u) | sed 's/^/+ /'
  comm -13 <(echo "$expected" | sort -u) <(echo "$actual" | sort -u) | sed 's/^/- /'
}

main "$@"
