#!/bin/bash
# vim: set ft=sh

set -e -x

cp $(which concourse) concourse-linux/concourse
cp $(which gdn) concourse-linux/gdn

cp -a /concourse-resource-types/ concourse-linux/resource-types/

mkdir concourse-linux/fly-assets
for platform in linux windows darwin; do
  if [ -d fly-linux ]; then
    cp -a fly-linux/fly-*.tgz concourse-linux/fly-assets
  fi
done

pushd concourse-linux
  archive=concourse-darwin-amd64.tgz
  tar -czf $archive concourse fly-assets gdn resource-types
  shasum "$archive" > "${archive}.sha1"
popd
