#!/bin/bash
# vim: set ft=sh

set -e -x

export GOPATH=$PWD/gopath
export PATH=$PWD/gopath/bin:$PATH

ldflags=""
if [ -e final-version/version ]; then
  final_version="$(cat final-version/version)"
  ldflags="-X main.Version=$final_version -X github.com/concourse/concourse/atc/atccmd.Version=$final_version"
fi

pushd concourse
  go build -ldflags "$ldflags" -o concourse ./bin/cmd/concourse
popd

mv concourse/concourse concourse-darwin/concourse

mkdir concourse-darwin/fly-assets
for platform in linux windows darwin; do
  if [ -e fly-$platform/fly-* ]; then
    cp -a fly-$platform/fly-* concourse-darwin/fly-assets
  fi
done

pushd concourse-darwin
  archive=concourse-darwin-amd64.tgz
  tar -czf $archive concourse fly-assets
  shasum "$archive" > "${archive}.sha1"
popd
