#!/bin/bash

set -e -u

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

source concourse/ci/tasks/scripts/docker-helpers.sh

# make loopback devices available for 'gdn' and the btrfs volume driver
# XXX: remove once 'gdn' doesn't need xfs and we're back to overlay as default
function create_loopbacks() {
  for i in $(seq 128 143); do
    mknod -m 0660 /dev/loop$i b 7 $i
  done
}

function cleanup_loopbacks() {
  for loop in $(losetup -a | cut -d: -f1); do
    losetup -d $loop
  done
}

concourse_dir=$PWD/concourse
if [ -d built-concourse ]; then
  concourse_dir=$PWD/built-concourse
fi

function cleanup() {
  docker-compose -f $concourse_dir/docker-compose.yml down
  stop_docker
  cleanup_loopbacks
}

trap cleanup EXIT

create_loopbacks
start_docker

[ -d dev-image ] && docker load -i dev-image/image.tar
[ -d postgres-image ] && docker load -i postgres-image/image.tar

cd $concourse_dir

# for better yarn output
stty columns 80
yarn install
yarn build

# do not collide with outer Concourse network
export CONCOURSE_GARDEN_NETWORK_POOL="10.224.0.0/16"
docker-compose up -d

until test $(curl -s -o /dev/null -w '%{http_code}' http://localhost:8080/api/v1/info) -eq 200; do
  echo "waiting for ATC..."
  sleep 1
done

go mod download

go install github.com/onsi/ginkgo/ginkgo

ginkgo -r -nodes=3 -race ./testflight "$@"
