#!/bin/bash

set -e -u

version=$(cat version/version)
latest_version=$(cat latest-version/version)

major_version=$(echo $version | cut -d. -f1)
minor_version=$(echo $version | cut -d. -f1,2)

latest_minor_version=$(echo $latest_version | cut -d. -f1,2)

echo $version       >> tags/tags
echo $minor_version >> tags/tags

# if the version we're publishing is for the latest minor version, bump the
# major and latest tags, too
if [ "$minor_version" = "$latest_minor_version" ]; then
  echo $major_version >> tags/tags
  echo latest         >> tags/tags
fi
