#!/bin/bash

set -e -u -x

export PIPELINE_NAME=test-pipeline

inputs=$PWD

source concourse/ci/tasks/scripts/docker-helpers.sh

start_docker

[ -d dev-image ] && docker load -i dev-image/image.tar
[ -d postgres-image ] && docker load -i postgres-image/image.tar

cd concourse

docker-compose up --build -d

./ci/tasks/scripts/create-upgrade-downgrade-pipeline

downgrade_to=$(docker run concourse/concourse:4.2.2 migrate --current-db-version)
docker-compose stop web
docker-compose run web migrate --migrate-db-to-version $downgrade_to

docker-compose -f docker-compose-4.2.2.yml up --remove-orphans -d

./ci/tasks/scripts/verify-upgrade-downgrade-pipeline

./ci/tasks/scripts/watsjs test/smoke.js
