#!/bin/bash
# vim: set ft=sh

set -e -x

export GOPATH=$PWD/gopath
export PATH=$PWD/gopath/bin:$PATH

platform="$(go env GOOS)"
arch="$(go env GOARCH)"

output="$PWD/fly-${platform}"

buildflags=""
if [ -e final-version/version ]; then
  final_version="$(cat final-version/version)"
  buildflags="-ldflags \"-X github.com/concourse/fly/version.Version=${final_version}\""
fi

pushd concourse
  CGO_ENABLED=0 go build $buildflags -o $output/fly ./fly
  if which ldd && ldd $output/fly 2>/dev/null; then
    echo "binary is not static; aborting"
    exit 1
  fi
popd

pushd $output
  archive=fly-$platform-$arch.tgz
  tar -czf $archive fly
  shasum "$archive" > "${archive}.sha1"
popd
