#!/bin/bash
# vim: set ft=sh

set -e -u

readonly SKIP="${SKIP:-}"

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

mkdir -p ~/.kube

if [ ! -f ~/.kube/config ]; then
  echo "$KUBE_CONFIG" > ~/.kube/config
fi

export CONCOURSE_IMAGE_DIGEST="$(cat concourse-rc-image/digest)"
export CONCOURSE_IMAGE_TAG="$(cat concourse-rc-image/tag)"
export CHARTS_DIR="$(realpath ./charts)"

cd concourse

go mod download

go install github.com/onsi/ginkgo/ginkgo

ginkgo -nodes=4 -race -keepGoing -slowSpecThreshold=300 -skip="$SKIP" ./topgun/k8s/ "$@"
