#!/bin/bash

# k8s-delete - deletes a helm deployment.

set -o errexit
set -o nounset

# name of the release to be deleted and purged.
readonly RELEASE_NAME="${RELEASE_NAME:-concourse-smoke}"

main() {
  eventually_populate_kube_config
  delete_release
}

eventually_populate_kube_config() {
  mkdir -p ~/.kube

  if [[ -f ~/.kube/config ]]; then
    return 0
  fi

  if [[ -z $KUBE_CONFIG ]]; then
    echo "Error: KUBE_CONFIG must be specified when ~/.kube/config doesnt exist"
    exit 1
  fi

  echo "$KUBE_CONFIG" >~/.kube/config
}

delete_release() {
  helm init --upgrade --wait
  helm version
  helm delete --purge $RELEASE_NAME
}

main "$@"
