#!/bin/bash
# vim: set ft=sh

set -e -u

readonly MAX_TICKS="${MAX_TICKS:-60}"

instance_ip="$(cat endpoint-info/instance_ip)"

test -n "$instance_ip"

export ATC_URL="http://${instance_ip}:8080"
export ATC_ADMIN_USERNAME=admin
if [ -e endpoint-info/admin_password ]; then
  export ATC_ADMIN_PASSWORD="$(cat endpoint-info/admin_password)"
else
  export ATC_ADMIN_PASSWORD=admin
fi

export ATC_GUEST_USERNAME=guest
export ATC_GUEST_PASSWORD=guest
if [ -e endpoint-info/guest_password ]; then
  export ATC_GUEST_PASSWORD="$(cat endpoint-info/guest_password)"
else
  export ATC_GUEST_PASSWORD=guest
fi

ticks=0
echo -n 'waiting for ATC to be running...'
until curl -sf "$ATC_URL/api/v1/info"; do
  echo -n .

  ((ticks++))

  if [ $ticks -ge $MAX_TICKS ]; then
    echo "giving up. :("
    exit 1
  fi

  sleep 1
done

echo 'ok!'

if curl "$ATC_URL/api/v1/cli?arch=amd64&platform=linux" -o /usr/local/bin/fly; then
  chmod +x /usr/local/bin/fly
else
  pushd concourse/fly
    go build -o /usr/local/bin/fly
  popd
fi

fly --version

$(dirname $0)/watsjs test/smoke.js
