#!/bin/bash
# vim: set ft=sh

set -e -u

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

cd concourse

go mod download

go install github.com/onsi/ginkgo/ginkgo

ginkgo -r -nodes=4 -race -keepGoing -slowSpecThreshold=15 ./testflight "$@"
