#!/bin/bash
# vim: set ft=sh

set -e

export GOPATH=${PWD}/concourse
export PATH=${PWD}/concourse/bin:$PATH

go install github.com/onsi/ginkgo/ginkgo

cd concourse/src/github.com/concourse/testflight/
ginkgo -r -nodes=3 -race "$@"
