#!/bin/bash
# vim: set ft=sh

set -e

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

eval $(ssh-agent)
ssh-add <(echo "$BOSH_KEY")

export CONCOURSE_RELEASE_VERSION="$(cat concourse-release/version)"
export BPM_RELEASE_VERSION="$(cat bpm-release/version)"
export POSTGRES_RELEASE_VERSION="$(cat postgres-release/version)"
export VAULT_RELEASE_VERSION="$(cat vault-release/version)"
export CREDHUB_RELEASE_VERSION="$(cat credhub-release/version)"
export GIT_SERVER_RELEASE_VERSION="$(cat git-server-release/version)"
export STEMCELL_VERSION="$(cat stemcell/version)"

bosh upload-release concourse-release/*.tgz
bosh upload-release bpm-release/*.tgz
bosh upload-release postgres-release/*.tgz
bosh upload-release git-server-release/*.tgz
bosh upload-release vault-release/*.tgz
bosh upload-release credhub-release/*.tgz
bosh upload-stemcell stemcell/*.tgz

cd concourse

go mod download

go install github.com/onsi/ginkgo/ginkgo

ginkgo -nodes=8 -race -keepGoing -slowSpecThreshold=300 -skip="$SKIP" ./topgun "$@"
