#!/bin/bash
# vim: set ft=sh

set -e -x

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

cd concourse

go mod download

go install github.com/onsi/ginkgo/ginkgo

ginkgo -r -p -race ./tsa "$@"
