#!/bin/bash
set -e -x

# alpine version concourse tgz package
mkdir -p tarball-contents

concourse_file_path=$(ls linux-rc/concourse-*.tgz)

tar -zxf $concourse_file_path -C tarball-contents

# iterate all directories of resource-types in concourse alpine tgz file
# replace alpine version of rootfs.tgz with ubuntu version
for res in tarball-contents/concourse/resource-types/*; do
  resource_name=$(basename $res)
  rm -rf tarball-contents/concourse/resource-types/$resource_name/*
  tar -zxf resources/$resource_name/*-ubuntu.tgz -C tarball-contents/concourse/resource-types/$resource_name/
  echo "replaced $resource_name"
done

# pack the concourse for linux release again
pushd tarball-contents
tar -czf ../ubuntu-linux-rc/$(basename $concourse_file_path) *
popd
