#!/bin/bash
set -e -x

# alpine version concourse tgz package
mkdir -p concourse-alpine

concourse_file_name=$(ls linux-rc/concourse-*.tgz)

tar -zxf $concourse_file_name -C concourse-alpine

# iterate all directories of resource-types in concourse alpine tgz file
# replace alpine version of rootfs.tgz with ubuntu version
for res in concourse-alpine/concourse/resource-types/*; do
  resource_name=$(basename $res)
  rm -rf concourse-alpine/concourse/resource-types/$resource_name/*
  tar -zxf resources/$resource_name/*-ubuntu.tgz -C concourse-alpine/concourse/resource-types/$resource_name/
  echo "replaced $resource_name"
done

# pack the concourse for linux release again
rm $concourse_file_name
pushd concourse-alpine
  tar -czf ../$concourse_file_name *
popd
