#!/bin/bash
# vim: set ft=sh

set -e -u

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

mkdir /tmp/concourse-pg-runner
if ! mount -t tmpfs none /tmp/concourse-pg-runner 2>/dev/null; then
  if grep '/dev/shm.*tmpfs' /proc/mounts >/dev/null; then
    mkdir /dev/shm/concourse-pg-runner
    rmdir /tmp/concourse-pg-runner
    ln -s /dev/shm/concourse-pg-runner /tmp/concourse-pg-runner
  else
    echo 'failed to mount tmpfs for pg. this is OK, db suite will just be slow'
  fi
fi

cd concourse

go mod download

go install github.com/onsi/ginkgo/ginkgo

ginkgo -r -p -race -skipPackage testflight,topgun "$@"
