#!/bin/bash
# vim: set ft=sh

set -e -u

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

mkdir /tmp/concourse-pg-runner
if ! mount -t tmpfs none /tmp/concourse-pg-runner; then
  echo 'failed to mount tmpfs for pg. this is OK, db suite will just be slow'
fi

cd concourse

go mod download

pushd web
  yarn
  make
popd

go install github.com/onsi/ginkgo/ginkgo

ginkgo -r -p -race -skipPackage testflight "$@"
