#!/bin/bash

set -e -u

source concourse/ci/tasks/scripts/docker-helpers.sh

start_docker

[ -d dev-image ] && docker load -i dev-image/image.tar
[ -d postgres-image ] && docker load -i postgres-image/image.tar

pushd concourse
  ./ci/tasks/scripts/generate-keys

  docker-compose \
    -f docker-compose.yml \
    -f ci/overrides/docker-compose.ci.yml \
    up --no-build -d
popd

"$@"

pushd concourse
  docker-compose down
popd

stop_docker
