#!/bin/bash

set -e -u

source concourse/ci/tasks/scripts/docker-helpers.sh

concourse_dir=$PWD/concourse
function cleanup() {
  docker-compose -f $concourse_dir/docker-compose.yml down
  stop_docker
}

trap cleanup EXIT

start_docker

[ -d dev-image ] && docker load -i dev-image/image.tar
[ -d postgres-image ] && docker load -i postgres-image/image.tar

pushd concourse
  # do not collide with outer Concourse network
  export CONCOURSE_GARDEN_NETWORK_POOL="10.224.0.0/16"
  docker-compose up -d
popd

"$@"
