#!/bin/bash
# vim: set ft=sh

set -e -x

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

export GOPATH=$PWD/concourse
export PATH=$GOPATH/bin:$PATH

go install github.com/onsi/ginkgo/ginkgo

cd ${GOPATH}/src/github.com/concourse/worker
ginkgo -r -p -race "$@"
