// Code generated by counterfeiter. DO NOT EDIT.
package accessorfakes

import (
	"sync"

	"github.com/concourse/concourse/atc/api/accessor"
	"github.com/concourse/concourse/atc/db"
)

type FakeAccessTokenFetcher struct {
	DeleteAccessTokenStub        func(string) error
	deleteAccessTokenMutex       sync.RWMutex
	deleteAccessTokenArgsForCall []struct {
		arg1 string
	}
	deleteAccessTokenReturns struct {
		result1 error
	}
	deleteAccessTokenReturnsOnCall map[int]struct {
		result1 error
	}
	GetAccessTokenStub        func(string) (db.AccessToken, bool, error)
	getAccessTokenMutex       sync.RWMutex
	getAccessTokenArgsForCall []struct {
		arg1 string
	}
	getAccessTokenReturns struct {
		result1 db.AccessToken
		result2 bool
		result3 error
	}
	getAccessTokenReturnsOnCall map[int]struct {
		result1 db.AccessToken
		result2 bool
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAccessTokenFetcher) DeleteAccessToken(arg1 string) error {
	fake.deleteAccessTokenMutex.Lock()
	ret, specificReturn := fake.deleteAccessTokenReturnsOnCall[len(fake.deleteAccessTokenArgsForCall)]
	fake.deleteAccessTokenArgsForCall = append(fake.deleteAccessTokenArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.DeleteAccessTokenStub
	fakeReturns := fake.deleteAccessTokenReturns
	fake.recordInvocation("DeleteAccessToken", []interface{}{arg1})
	fake.deleteAccessTokenMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAccessTokenFetcher) DeleteAccessTokenCallCount() int {
	fake.deleteAccessTokenMutex.RLock()
	defer fake.deleteAccessTokenMutex.RUnlock()
	return len(fake.deleteAccessTokenArgsForCall)
}

func (fake *FakeAccessTokenFetcher) DeleteAccessTokenCalls(stub func(string) error) {
	fake.deleteAccessTokenMutex.Lock()
	defer fake.deleteAccessTokenMutex.Unlock()
	fake.DeleteAccessTokenStub = stub
}

func (fake *FakeAccessTokenFetcher) DeleteAccessTokenArgsForCall(i int) string {
	fake.deleteAccessTokenMutex.RLock()
	defer fake.deleteAccessTokenMutex.RUnlock()
	argsForCall := fake.deleteAccessTokenArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAccessTokenFetcher) DeleteAccessTokenReturns(result1 error) {
	fake.deleteAccessTokenMutex.Lock()
	defer fake.deleteAccessTokenMutex.Unlock()
	fake.DeleteAccessTokenStub = nil
	fake.deleteAccessTokenReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAccessTokenFetcher) DeleteAccessTokenReturnsOnCall(i int, result1 error) {
	fake.deleteAccessTokenMutex.Lock()
	defer fake.deleteAccessTokenMutex.Unlock()
	fake.DeleteAccessTokenStub = nil
	if fake.deleteAccessTokenReturnsOnCall == nil {
		fake.deleteAccessTokenReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteAccessTokenReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAccessTokenFetcher) GetAccessToken(arg1 string) (db.AccessToken, bool, error) {
	fake.getAccessTokenMutex.Lock()
	ret, specificReturn := fake.getAccessTokenReturnsOnCall[len(fake.getAccessTokenArgsForCall)]
	fake.getAccessTokenArgsForCall = append(fake.getAccessTokenArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetAccessTokenStub
	fakeReturns := fake.getAccessTokenReturns
	fake.recordInvocation("GetAccessToken", []interface{}{arg1})
	fake.getAccessTokenMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeAccessTokenFetcher) GetAccessTokenCallCount() int {
	fake.getAccessTokenMutex.RLock()
	defer fake.getAccessTokenMutex.RUnlock()
	return len(fake.getAccessTokenArgsForCall)
}

func (fake *FakeAccessTokenFetcher) GetAccessTokenCalls(stub func(string) (db.AccessToken, bool, error)) {
	fake.getAccessTokenMutex.Lock()
	defer fake.getAccessTokenMutex.Unlock()
	fake.GetAccessTokenStub = stub
}

func (fake *FakeAccessTokenFetcher) GetAccessTokenArgsForCall(i int) string {
	fake.getAccessTokenMutex.RLock()
	defer fake.getAccessTokenMutex.RUnlock()
	argsForCall := fake.getAccessTokenArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAccessTokenFetcher) GetAccessTokenReturns(result1 db.AccessToken, result2 bool, result3 error) {
	fake.getAccessTokenMutex.Lock()
	defer fake.getAccessTokenMutex.Unlock()
	fake.GetAccessTokenStub = nil
	fake.getAccessTokenReturns = struct {
		result1 db.AccessToken
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAccessTokenFetcher) GetAccessTokenReturnsOnCall(i int, result1 db.AccessToken, result2 bool, result3 error) {
	fake.getAccessTokenMutex.Lock()
	defer fake.getAccessTokenMutex.Unlock()
	fake.GetAccessTokenStub = nil
	if fake.getAccessTokenReturnsOnCall == nil {
		fake.getAccessTokenReturnsOnCall = make(map[int]struct {
			result1 db.AccessToken
			result2 bool
			result3 error
		})
	}
	fake.getAccessTokenReturnsOnCall[i] = struct {
		result1 db.AccessToken
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAccessTokenFetcher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.deleteAccessTokenMutex.RLock()
	defer fake.deleteAccessTokenMutex.RUnlock()
	fake.getAccessTokenMutex.RLock()
	defer fake.getAccessTokenMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAccessTokenFetcher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ accessor.AccessTokenFetcher = new(FakeAccessTokenFetcher)
