resource_types:
- name: smuggler
  type: docker-image
  source:
    repository: redfactorlabs/concourse-smuggler-resource
    tag: ubuntu-14.04

- name: custom-resource-type
  type: docker-image
  source:
    repository: ((resource_type_repository))

resources:
- name: custom-resource
  type: custom-resource-type
  source:
    interval: ((time_resource_interval))

- name: some-resource
  type: time
  source:
    interval: ((time_resource_interval))

- name: my_smuggler_resource
  type: smuggler
  source:
    commands:
      check: 'echo version > ${SMUGGLER_OUTPUT_DIR}/versions'
      in: 'echo GET SECRET: $SMUGGLER_SECRET_USERNAME/$SMUGGLER_SECRET_PASSWORD'
      out: 'echo PUT SECRET: $SMUGGLER_SECRET_USERNAME/$SMUGGLER_SECRET_PASSWORD; echo new-version > ${SMUGGLER_OUTPUT_DIR}/versions'

jobs:
- name: job-with-input
  plan:
  - get: some-resource
  - get: my_smuggler_resource
    params:
      smuggler_params:
        SECRET_USERNAME: GET-((job_secret.username))
        SECRET_PASSWORD: GET-((job_secret.password))
  - put: my_smuggler_resource
    params:
      smuggler_params:
        SECRET_USERNAME: PUT-((job_secret.username))
        SECRET_PASSWORD: PUT-((job_secret.password))
    get_params:
      smuggler_params:
        SECRET_USERNAME: PUT-GET-((job_secret.username))
        SECRET_PASSWORD: PUT-GET-((job_secret.password))
  - task: simple-task
    params:
      SECRET_USERNAME: ((job_secret.username))
      SECRET_PASSWORD: ((job_secret.password))
      TEAM_SECRET: ((team_secret))
    config:
      platform: linux

      image_resource:
        type: docker-image
        source: {repository: ((image_resource_repository))}

      params:
        SECRET:

      run:
        path: sh
        args: ['-c', 'echo TASK SECRET: $SECRET_USERNAME/$SECRET_PASSWORD, TEAM SECRET: $TEAM_SECRET']

- name: job-with-custom-input
  plan:
  - get: custom-resource
  - get: my_smuggler_resource
    params:
      smuggler_params:
        SECRET_USERNAME: GET-((job_secret.username))
        SECRET_PASSWORD: GET-((job_secret.password))
  - put: my_smuggler_resource
    params:
      smuggler_params:
        SECRET_USERNAME: PUT-((job_secret.username))
        SECRET_PASSWORD: PUT-((job_secret.password))
    get_params:
      smuggler_params:
        SECRET_USERNAME: PUT-GET-((job_secret.username))
        SECRET_PASSWORD: PUT-GET-((job_secret.password))
  - task: simple-task
    params:
      SECRET_USERNAME: ((job_secret.username))
      SECRET_PASSWORD: ((job_secret.password))
      TEAM_SECRET: ((team_secret))
    config:
      platform: linux

      image_resource:
        type: docker-image
        source: {repository: ((image_resource_repository))}

      params:
        SECRET:

      run:
        path: sh
        args: ['-c', 'echo TASK SECRET: $SECRET_USERNAME/$SECRET_PASSWORD, TEAM SECRET: $TEAM_SECRET']
