// Code generated by mockery v1.0.0. DO NOT EDIT.

package cmocks

import (
	db "github.com/concourse/concourse/atc/db"
	mock "github.com/stretchr/testify/mock"
)

// NotificationsBus is an autogenerated mock type for the NotificationsBus type
type NotificationsBus struct {
	mock.Mock
}

// Listen provides a mock function with given fields: _a0, _a1
func (_m *NotificationsBus) Listen(_a0 string, _a1 db.NotificationQueueMode) (chan db.Notification, error) {
	ret := _m.Called(_a0, _a1)

	var r0 chan db.Notification
	if rf, ok := ret.Get(0).(func(string, db.NotificationQueueMode) chan db.Notification); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan db.Notification)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, db.NotificationQueueMode) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Unlisten provides a mock function with given fields: _a0, _a1
func (_m *NotificationsBus) Unlisten(_a0 string, _a1 chan db.Notification) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, chan db.Notification) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
