package styles

import (
	"github.com/alecthomas/chroma"
	"github.com/alecthomas/chroma/styles"
)

// ConcourseCI style.
var ConcourseCI = styles.Register(chroma.MustNewStyle("concourseci", chroma.StyleEntries{
	chroma.LineHighlight:            "bg:#ffffcc",
	chroma.Comment:                  "#BDC3C7",
	chroma.Error:                    "#E74C3C",
	chroma.Keyword:                  "#2ECC71 bold",
	chroma.CommentMultiline:         "#BDC3C7",
	chroma.CommentPreproc:           "#E74C3C bold",
	chroma.CommentSingle:            "#BDC3C7",
	chroma.CommentSpecial:           "#E74C3C bold",
	chroma.GenericDeleted:           "#1A252F bg:#ffdddd",
	chroma.GenericEmph:              "italic",
	chroma.GenericError:             "#E74C3C",
	chroma.GenericHeading:           "#34495E",
	chroma.GenericInserted:          "#1A252F bg:#ddffdd",
	chroma.GenericOutput:            "#BDC3C7",
	chroma.GenericPrompt:            "#5D6D7E",
	chroma.GenericStrong:            "bold",
	chroma.GenericSubheading:        "#BDC3C7",
	chroma.GenericTraceback:         "#E74C3C",
	chroma.KeywordConstant:          "#2ECC71 bold",
	chroma.KeywordDeclaration:       "#2ECC71 bold",
	chroma.KeywordNamespace:         "#2ECC71 bold",
	chroma.KeywordPseudo:            "#2ECC71",
	chroma.KeywordReserved:          "#2ECC71 bold",
	chroma.KeywordType:              "#BDC3C7 bold",
	chroma.LiteralNumber:            "#1ABC9C bold",
	chroma.LiteralString:            "#2ECC71",
	chroma.NameAttribute:            "#3498DB",
	chroma.NameBuiltin:              "#8F4B2D",
	chroma.NameClass:                "#9B59B6 bold",
	chroma.NameConstant:             "#1ABC9C bold",
	chroma.NameDecorator:            "#5D6D7E",
	chroma.NameException:            "#9B59B6 bold",
	chroma.NameFunction:             "#1ABC9C bold",
	chroma.NameLabel:                "#3498DB italic",
	chroma.NameNamespace:            "#9B59B6 bold",
	chroma.NameProperty:             "#3498DB bold",
	chroma.NameTag:                  "#9B59B6 bold",
	chroma.NameVariable:             "#3498DB",
	chroma.OperatorWord:             "#2ECC71",
	chroma.TextWhitespace:           "#E6E7E8",
	chroma.LiteralNumberFloat:       "#1ABC9C bold",
	chroma.LiteralNumberHex:         "#1ABC9C bold",
	chroma.LiteralNumberInteger:     "#1ABC9C bold",
	chroma.LiteralNumberOct:         "#1ABC9C bold",
	chroma.LiteralStringBacktick:    "#E67E22",
	chroma.LiteralStringChar:        "#E67E22",
	chroma.LiteralStringDoc:         "#E67E22",
	chroma.LiteralStringDouble:      "#E67E22",
	chroma.LiteralStringEscape:      "#3498DB",
	chroma.LiteralStringHeredoc:     "#E67E22",
	chroma.LiteralStringInterpol:    "#1ABC9C",
	chroma.LiteralStringOther:       "#F1C40F",
	chroma.LiteralStringRegex:       "#2ECC71",
	chroma.LiteralStringSingle:      "#E74C3C",
	chroma.LiteralStringSymbol:      "#F1C40F",
	chroma.NameBuiltinPseudo:        "#8F4B2D",
	chroma.NameVariableClass:        "#3498DB",
	chroma.NameVariableGlobal:       "#F1C40F",
	chroma.NameVariableInstance:     "#1ABC9C",
	chroma.LiteralNumberIntegerLong: "#1ABC9C bold",
}))
