#!/bin/bash

set -e -u -x

LINUX_ASSETS=$PWD/linux

rm -rf $LINUX_ASSETS
mkdir -p $LINUX_ASSETS

mkdir -p $LINUX_ASSETS/bin
cp /opt/static-assets/tar $LINUX_ASSETS/bin/tar

mkdir -p $LINUX_ASSETS/btrfs
cp /opt/static-assets/btrfs /opt/static-assets/mkfs.btrfs $LINUX_ASSETS/btrfs

cp -a /opt/static-assets/iptables $LINUX_ASSETS/iptables

# go-bindata does weird stuff with symlinks. we only care about iptables anyway
rm /opt/static-assets/iptables/sbin/*
rm -r /opt/static-assets/iptables/bin
cp -aL /opt/static-assets/iptables/sbin/iptables $LINUX_ASSETS/iptables/sbin/iptables

pushd guardian-release/
  # workaround 'mv /root/.tmp/... /tmp/...: invalid cross-device link'
  HOME=$PWD bosh sync-blobs

  cp -L blobs/busybox/busybox.tar.gz $LINUX_ASSETS/busybox.tar.gz

  (
    set -e -u -x

    export GOPATH=$PWD

    go install github.com/cloudfoundry-incubator/guardian/cmd/dadoo
    go install github.com/cloudfoundry-incubator/guardian/cmd/init
    go install github.com/cloudfoundry-incubator/guardian/cmd/kawasaki
    go install github.com/cloudfoundry-incubator/guardian/rundmc/iodaemon/cmd/iodaemon

    GOPATH=$PWD/src/github.com/opencontainers/runc/Godeps/_workspace:$GOPATH \
      go install github.com/opencontainers/runc

    pushd src/github.com/cloudfoundry-incubator/guardian/rundmc/nstar
      make
      mv nstar $LINUX_ASSETS/bin
    popd

    cp bin/{iodaemon,kawasaki,init,runc,dadoo} $LINUX_ASSETS/bin
  )
popd

pushd concourse/
  # workaround 'mv /root/.tmp/... /tmp/...: invalid cross-device link'
  HOME=$PWD bosh sync-blobs

  mkdir -p $LINUX_ASSETS/resources

  for resource in blobs/resources/*-resource.tar.gz; do
    resource_name="$(basename $resource | sed -e 's/-resource.tar.gz//')"
    cp -L "$resource" $LINUX_ASSETS/resources/$resource_name
  done
popd
