#!/bin/bash

set -e -u -x

LINUX_ASSETS=$PWD/linux

rm -rf $LINUX_ASSETS
mkdir -p $LINUX_ASSETS

mkdir -p $LINUX_ASSETS/bin
cp /opt/static-assets/tar $LINUX_ASSETS/bin/tar

mkdir -p $LINUX_ASSETS/btrfs
cp /opt/static-assets/btrfs /opt/static-assets/mkfs.btrfs $LINUX_ASSETS/btrfs

pushd garden-linux-release/
  # workaround 'mv /root/.tmp/... /tmp/...: invalid cross-device link'
  HOME=$PWD bosh sync-blobs

  cp -L blobs/busybox/busybox.tar.gz $LINUX_ASSETS/busybox.tar.gz

  (
    set -e -u -x

    export GOPATH=$PWD

    cd ./src/github.com/cloudfoundry-incubator/garden-linux
    make
    cp -a out/garden-linux $LINUX_ASSETS/garden-linux
    cp -a linux_backend/bin/* $LINUX_ASSETS/bin/
    cp -a linux_backend/skeleton $LINUX_ASSETS/skeleton
  )
popd

pushd concourse/
  # workaround 'mv /root/.tmp/... /tmp/...: invalid cross-device link'
  HOME=$PWD bosh sync-blobs

  mkdir -p $LINUX_ASSETS/resources

  for resource in blobs/resources/*-resource.tar.gz; do
    resource_name="$(basename $resource | sed -e 's/-resource.tar.gz//')"
    cp -L "$resource" $LINUX_ASSETS/resources/$resource_name
  done
popd
