#!/bin/bash

set -e -u

cd $(dirname $0)/..

go install github.com/vito/booklit/cmd/booklit

booklit -i lit/index.lit -o . \
  --save-search-index \
  --html-templates html/ \
  --plugin github.com/concourse/docs/go/docs \
  --plugin github.com/concourse/docs/go/resource-type-list \
  "$@"
