#!/bin/bash

set -e -x

ROOT=$(cd $(dirname $0)/.. && pwd)

if [ ! -e garden-linux-release ]; then
  git clone https://github.com/cloudfoundry-incubator/garden-linux-release --recursive
fi

if [ ! -e concourse ]; then
  git clone https://github.com/concourse/concourse
fi

if [ ! -e tar ]; then
  curl https://ftp.gnu.org/gnu/tar/tar-1.28.tar.gz | tar zxf -
  mv tar-1.28 tar
fi

if [ ! -e btrfs-progs ]; then
  curl https://www.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v4.4.tar.gz | tar zxf -
  mv btrfs-progs-v4.4 btrfs-progs
fi

apt-get update

if ! which bosh 2>/dev/null 2>&1; then
  apt-get -y install ruby
  gem install bosh_cli --no-rdoc --no-ri
fi

rm -rf $ROOT/linux
mkdir -p $ROOT/linux

pushd garden-linux-release/
  export GOPATH=$PWD

  bosh --parallel 3 sync blobs

  cp -L blobs/busybox/busybox.tar.gz $ROOT/linux/busybox.tar.gz

  pushd ./src/github.com/cloudfoundry-incubator/garden-linux
    make
    cp -a out/garden-linux $ROOT/linux/garden-linux
    cp -a linux_backend/bin $ROOT/linux/bin
    cp -a linux_backend/skeleton $ROOT/linux/skeleton
  popd
popd

pushd tar/
  FORCE_UNSAFE_CONFIGURE=1 ./configure
  make LDFLAGS=-static
  cp src/tar $ROOT/linux/bin/tar
popd

pushd btrfs-progs/
  apt-get -y install liblzo2-dev libblkid-dev e2fslibs-dev pkg-config libz-dev

  LDFLAGS=-static ./configure --disable-documentation
  make

  mkdir -p $ROOT/linux/btrfs
  cp btrfs $ROOT/linux/btrfs
  cp mkfs.btrfs $ROOT/linux/btrfs
popd

pushd concourse/
  mkdir -p $ROOT/linux/resources

  bosh --parallel 3 sync blobs

  for resource in blobs/resources/*-resource.tar.gz; do
    resource_name="$(basename $resource | sed -e 's/-resource.tar.gz//')"
    cp -L "$resource" $ROOT/linux/resources/$resource_name
  done
popd
