#!/bin/bash

set -e -x

ROOT=$(cd $(dirname $0)/.. && pwd)

if [ ! -e concourse ]; then
  git clone https://github.com/concourse/concourse --recursive
fi

cd concourse/

export GOPATH=$PWD

cd ./src/github.com/concourse/atc

mkdir -p $ROOT/atc
go build -o $ROOT/atc/atc github.com/concourse/atc/cmd/atc
