#!/bin/bash

set -e -u

cd $(dirname $0)/..

export GOPATH=$PWD
export PATH=$PWD/bin:$PATH

go install github.com/vito/booklit/cmd/booklit

booklit -i lit/index.lit -o . \
  --html-templates html/ \
  --plugin concourse-lit/splash \
  --plugin concourse-lit/resources-table \
  --plugin concourse-lit/docs \
  --plugin concourse-lit/community "$@"

booklit -i lit/single-page.lit -o . \
  --html-templates html/ \
  --plugin concourse-lit/splash \
  --plugin concourse-lit/resources-table \
  --plugin concourse-lit/docs \
  --plugin concourse-lit/community \
  --allow-broken-references
