#!/bin/bash

set -e -x

ROOT=$(cd $(dirname $0)/.. && pwd)

if [ ! -e garden-linux-release ]; then
  git clone https://github.com/cloudfoundry-incubator/garden-linux-release --recursive
fi

if [ ! -e concourse ]; then
  git clone https://github.com/concourse/concourse
fi

if [ ! -e tar ]; then
  curl https://ftp.gnu.org/gnu/tar/tar-1.28.tar.gz | tar zxf -
  mv tar-1.28 tar
fi

pushd garden-linux-release/
  export GOPATH=$PWD

  pushd ./src/github.com/cloudfoundry-incubator/garden-linux
    make
    rm -rf $ROOT/linux
    mkdir -p $ROOT/linux
    cp -a out/garden-linux $ROOT/linux/garden-linux
    cp -a linux_backend/bin $ROOT/linux/bin
    cp -a linux_backend/skeleton $ROOT/linux/skeleton
  popd
popd

pushd tar/
  ./configure
  make LDFLAGS=-static
  cp src/tar $ROOT/linux/bin/tar
popd

pushd concourse/
  mkdir -p $ROOT/linux/resources

  bosh sync blobs

  for resource in blobs/resources/*-resource.tar.gz; do
    resource_name="$(basename $resource | sed -e 's/-resource.tar.gz//')"
    cp -L "$resource" $ROOT/linux/resources/$resource_name
  done
popd
