#!/bin/bash
# vim: set ft=sh

set -e -x

pushd atc/
  export ATC_SHA=$(git rev-parse HEAD)
popd

pushd turbine/
  export TURBINE_SHA=$(git rev-parse HEAD)
popd

pushd garden-linux/
  export GARDEN_LINUX_SHA=$(git rev-parse HEAD)
popd

cd concourse-dev/

git config --global user.email "ci@localhost"
git config --global user.name "CI Bot"

git merge --no-edit master

git submodule update --remote

pushd src/atc/
  git checkout $ATC_SHA
popd

pushd src/turbine/
  git checkout $TURBINE_SHA
popd

pushd src/garden-linux/
  git checkout $GARDEN_LINUX_SHA
popd

git add src/

git commit -m "auto-bump"
