#!/bin/bash
# vim: set ft=sh

set -e -x

source ./deployments/sandbox/bosh_environment

VERSION=$(cat ./version/number)
if [ -z "$VERSION" ]; then
  echo "missing version number"
  exit 1
fi

cp deployments/sandbox/config/private.yml concourse-dev/config/private.yml

cd concourse-dev/

git merge master

./generate_deployment_manifest aws ../deployments/sandbox/stubs/*.yml > aws-deployment.yml

bosh target ${BOSH_TARGET}

bosh deployment aws-deployment.yml

if [ -f ../bosh-stemcells/*.tgz ]; then
  bosh -n upload stemcell ../bosh-stemcells/*.tgz --skip-if-exists
fi

bosh -n create release --final --with-tarball --version "$VERSION"

bosh -n upload release --skip-if-exists

yes yes | bosh deploy

git add -A
git commit -m "release v${VERSION}"
