#!/bin/bash
# vim: set ft=sh

set -e -x

source ./deployments/sandbox/bosh_environment

cd concourse/

./generate_deployment_manifest aws ../deployments/sandbox/stubs/*.yml > aws-deployment.yml

bosh target ${BOSH_TARGET}

bosh deployment aws-deployment.yml

if [ -f ../bosh-stemcells/*.tgz ]; then
  bosh -n upload stemcell ../bosh-stemcells/*.tgz --skip-if-exists
fi

bosh -n create release

# remove '|| true' once the rebase crap is fixed
bosh -n upload release --rebase --skip-if-exists || true

yes yes | bosh deploy
