#!/bin/bash
# vim: set ft=sh

set -e -x

source ./deployments/ci/bosh_environment

VERSION=$(cat ./version/number)
if [ -z "$VERSION" ]; then
  echo "missing version number"
  exit 1
fi

cp deployments/ci/config/private.yml concourse-dev/config/private.yml

cd concourse-dev/

git config --global user.email "ci@localhost"
git config --global user.name "CI Bot"

git merge --no-edit master

bosh target ${BOSH_TARGET}

bosh deployment ../deployments/ci/deployments/concourse.yml

if [ -f ../bosh-stemcells/*.tgz ]; then
  bosh -n upload stemcell ../bosh-stemcells/*.tgz --skip-if-exists
fi

bosh -n create release --final --version "$VERSION"
bosh -n upload release --skip-if-exists

bosh -n deploy
