#!/bin/bash
# vim: set ft=sh

set -e -x

REPOS="
  github.com/concourse/testflight
  github.com/winston-ci/winston
  github.com/winston-ci/smith
  github.com/winston-ci/redgreen
  github.com/winston-ci/prole
  github.com/cloudfoundry-incubator/warden-linux
"

DEV_GOPATH=$(cd ${1:-$HOME/go} && pwd)
TMP_DIR=/tmp/testflight
TMP_GOPATH=${TMP_DIR}/gopath

mkdir -p ${TMP_GOPATH}

cp $(dirname $0)/build.yml ${TMP_DIR}/build.yml

rsync --del --exclude '.*' -a ~/workspace/resource-images/ ${TMP_DIR}/resource-images/

go test -c
rm testflight.test

function copy_to_gopath {
  mkdir -p ${TMP_GOPATH}/src/${1}
  rsync --del --exclude '.*' -a ${DEV_GOPATH}/src/${1}/ ${TMP_GOPATH}/src/${1}/
}

pushd $TMP_GOPATH
  go get $(for repo in $REPOS; do echo -n " $repo/..."; done)
  godep save $(for repo in $REPOS; do echo -n " $repo/..."; done)

  rsync --del --exclude '.*' -a Godeps/_workspace/src/ src/
  rm -rf Godeps
popd

# grab and set up our components
for repo in $REPOS; do
  copy_to_gopath $repo &
done

wait

cd ${TMP_DIR}
smith
