#!/bin/bash

set -e -u

go-bindata \
  -pkg migration \
  -o db/migration/bindata.go \
  -prefix db/migration/migrations/ \
  -ignore 'db/migration/migrations/migrations.go' \
  db/migration/migrations/*
