#!/bin/bash

cd $(dirname $0)/..

director_uuid=$(bosh status --uuid)

cat deployment.yml | sed "s/director_uuid: ~/director_uuid: $director_uuid/g" > scripts/manifests/deployment.yml

if [ -z "$(bosh -v)" ]; then
  bosh update-cloud-config cloud_config.yml
  bosh -d concourse-testflight deploy scripts/manifests/deployment.yml "$@"
else
  bosh update cloud-config cloud_config.yml
  bosh -d scripts/manifests/deployment.yml deploy "$@"
fi
