#!/bin/sh

set -e -x

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TESTFLIGHT_DIR="$( cd "${MY_DIR}/.." && pwd )"

export GARDEN_LINUX_VERSION=latest

bosh target 192.168.50.4

pushd "${TESTFLIGHT_DIR}"
  ginkgo -r -v "$@"
popd
