#!/bin/bash

cd $(dirname $0)

if [ -z "$(bosh -v)" ]; then
  bosh update-cloud-config manifests/cloud_config.yml
  bosh -d concourse-testflight deploy manifests/deployment.yml "$@"
else
  director_uuid=$(bosh status --uuid)
  bosh update cloud-config manifests/cloud_config.yml
  bosh -d <(cat manifests/deployment.yml | sed "s/director_uuid: ~/director_uuid: $director_uuid/g") -n deploy "$@"
fi
