#!/bin/bash
# vim: set ft=sh

set -e -x

# set up cgroups
mkdir -p /sys/fs/cgroup
cgroups-mount

SETTINGS_FLAVOR=dev docker-registry &

until curl http://127.0.0.1:5000; do
  echo waiting for registry on port 5000...
  sleep 1;
done

# bullshit
mount -t tmpfs -o remount,size=1G none /dev/shm

# docker graph dir
mkdir -p /var/lib/docker
mount -t tmpfs -o size=1G none /var/lib/docker

# start docker for building resource images
service docker.io start

until [ -S /var/run/docker.sock ]; do
  echo waiting for docker to come up...
  sleep 0.5
done

pushd $GOPATH/resource-images
  docker.io build -t localhost:5000/raw-resource raw
  docker.io push localhost:5000/raw-resource
popd

# no longer need docker running
service docker.io stop

# set up a $TMPDIR so warden's graphs go onto tmpfs
mkdir -p /tmp/testflight
export TMPDIR=/tmp/testflight
mount -t tmpfs -o size=1G none /tmp/testflight
