#!/bin/sh

cd $(dirname $0)/..

set -e -x

./scripts/sync-submodule-config

./scripts/sync-package-specs
git add packages/*/spec

./scripts/scan-for-secrets

./scripts/commit-with-submodule-log "$@"

git ci --amend --reset-author

echo "If there are still untracked files, please add them and run ./scripts/scan-for-secrets before proceeding"

