#!/bin/bash

set -e -u -x

workdir=/etc/concourse

session_key=$workdir/session-key
tsa_key=$workdir/tsa-key
worker_key=$workdir/worker-key

sudo mkdir -p $workdir
sudo chown $(whoami) $workdir

for key in $session_key $tsa_key $worker_key; do
  [ -e "$key" ] || ssh-keygen -N '' -t rsa -f "$key"
done

concourse=$(which concourse)
if [ -z "$concourse" ]; then
  echo "'concourse' must be installed someplace in your \$PATH" >&2
  exit 1
fi

$concourse web \
  --log-level debug \
  --add-local-user test:test \
  --main-team-allow-all-users \
  --session-signing-key $session_key \
  --tsa-bind-port 2223 \
  --tsa-host-key $tsa_key \
  --tsa-authorized-keys ${worker_key}.pub &

trap "kill $!" 0

sudo $concourse worker \
  --work-dir $workdir \
  --tsa-port 2223 \
  --tsa-public-key ${tsa_key}.pub \
  --tsa-worker-private-key $worker_key \
  --peer-ip 127.0.0.1
