#!/bin/bash

set -e -u

cd $(dirname $0)/..

tag_name="$1"
shift

go install github.com/vito/booklit/cmd/booklit

booklit -i lit/index.lit \
  --plugin github.com/concourse/docs/go/docs \
  --plugin github.com/concourse/docs/go/resource-type-list \
  --html-templates html/release-notes/ \
  --tag "$tag_name" \
  "$@"
