#!/bin/bash

set -e -u

cd $(dirname $0)/..

version="$1"
shift

go install github.com/vito/booklit/cmd/booklit

booklit -i lit/index.lit \
  --plugin github.com/concourse/docs/go/docs \
  --plugin github.com/concourse/docs/go/resource-type-list \
  --text-file-extension md \
  --text-templates md/ \
  --section-path lit/release-notes/$version.lit \
  "$@"
