#!/bin/sh

if [ ! -f "./.gitmodules" ]; then
  echo "this script can only be run from the outer concourse repo, otherwise it would scan the wrong files"
  exit 1
fi

scan_for_secrets () {
  git secrets --scan --recursive && git submodule foreach git secrets --scan --recursive
}

if ! scan_for_secrets; then
  cat << EOF
Scan for secrets failed! Make sure you have run the following commands to add known exceptions:
git secrets --register-aws --global
git secrets --add --global -a 81030000000050971041
git secrets --add --global -a 91024019000000000000
git secrets --add --global -a GO15VENDOREXPERIMENT
git secrets --add --global -a 01020102030405060708
git secrets --add --global -a 18446744073709551615
git secrets --add --global -a 18446744073709551616
EOF
  exit 1
fi

