#!/bin/bash
# vim: set ft=sh

set -e -x

source ./deployments/ci/bosh_environment

VERSION=$(cat ./version/number)
if [ -z "$VERSION" ]; then
  echo "missing version number"
  exit 1
fi

cp deployments/ci/config/private.yml concourse-dev/config/private.yml

cd concourse-dev/

git config --global user.email "ci@localhost"
git config --global user.name "CI Bot"

git merge --no-edit master

bosh target ${BOSH_TARGET}

bosh -n create release --final --with-tarball --version "$VERSION"
bosh -n upload release --skip-if-exists

git add -A
git commit -m "release v${VERSION}"
