#!/usr/bin/env ruby
require_relative 'check_travis.rb'

diffs = `git diff --cached`.split('diff --git').select { |log| log =~ /Subproject/ }

locations = {}
diffs.each do |diff|
  /a\/(?<loc>.+?)\sb.*index\s(?<shas>\S+)/m.match diff do |matches|
    locations[matches[:loc]] = matches[:shas]
  end
end

puts "Bump #{locations.keys.join(", ")}"
puts # Second line of git commit message should always be empty

locations.each do |location, shas|
  Dir.chdir(location) do
    travis = TravisBuild.new(shas, ARGV[0] == "-c")
    travis.log_sorted_by_author_with_travis_status
  end if Dir.exists?(location)
end
