#!/bin/bash
# vim: set ft=sh

gosub list \
  -a github.com/concourse/fly \
  -a github.com/concourse/turbine/cmd/... \
  -a github.com/concourse/atc/cmd/... \
  -a github.com/concourse/blackbox/cmd/... \
  -t github.com/concourse/testflight/... \
  -a github.com/vito/gosub \
  | xargs gosub sync
