#!/bin/bash
# vim: set ft=sh

gosub list \
  -a github.com/concourse/fly \
  -a github.com/concourse/turbine \
  -a github.com/concourse/atc \
  -t github.com/concourse/testflight/... \
  -a github.com/vito/gosub \
  | xargs gosub sync
