#!/bin/bash
# vim: set ft=sh

set -e -x

export GOROOT=/usr/local/go
export PATH=${GOROOT}/bin:$PATH

export BASE_GOPATH=${PWD}/gopath
export PATH=${BASE_GOPATH}/bin:$PATH

export EXTERNAL_ADDRESS=$(ip route get 8.8.8.8 | sed 's/.*src\s\(.*\)\s/\1/;tx;d;:x')

pushd godeps/src/github.com/cloudfoundry-incubator/warden-linux/
  make # compile wshd/etc.
  export WARDEN_BINPATH=${PWD}/linux_backend/bin
popd

cd godeps/src/github.com/concourse/testflight

export GOPATH=${BASE_GOPATH}:${PWD}/Godeps/_workspace
export PATH=${PWD}/Godeps/_workspace/bin:$PATH

go install github.com/onsi/ginkgo/ginkgo

# set up a $TMPDIR so warden's graphs go onto tmpfs
mkdir -p /tmp/testflight
mount -t tmpfs -o size=1G none /tmp/testflight
export TMPDIR=/tmp/testflight

# make /dev/shm larger
mount -t tmpfs -o remount,size=1G none /dev/shm

ginkgo -r -v
