#!/bin/bash
# vim: set ft=sh

set -e -x

export PATH=/usr/lib/postgresql/9.3/bin:$PATH

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

export BASE_GOPATH=${PWD}/gopath

export GOPATH=${BASE_GOPATH}
export PATH=${BASE_GOPATH}/bin:$PATH

export EXTERNAL_ADDRESS=$(ip route get 8.8.8.8 | sed 's/.*src\s\(.*\)\s/\1/;tx;d;:x')

export ARCHIVE_RESOURCE_ROOTFS=/tmp/archive-resource-rootfs
export GIT_RESOURCE_ROOTFS=/tmp/git-resource-rootfs
export HELPER_ROOTFS=/tmp/helper-rootfs

mkdir -p $ARCHIVE_RESOURCE_ROOTFS
tar -C $ARCHIVE_RESOURCE_ROOTFS -xf dev-archive-resource-image/rootfs.tar

mkdir -p $GIT_RESOURCE_ROOTFS
tar -C $GIT_RESOURCE_ROOTFS -xf dev-git-resource/rootfs.tar

mkdir -p $HELPER_ROOTFS
tar -C $HELPER_ROOTFS -xf testflight-helper/rootfs.tar

pushd gopath/src/github.com/cloudfoundry-incubator/warden-linux/
  make # compile wshd/etc.
  export WARDEN_BINPATH=$PWD/linux_backend/bin
popd

cd gopath/src/github.com/concourse/testflight/

export GOPATH=${PWD}/Godeps/_workspace:${GOPATH}
export PATH=${PWD}/Godeps/_workspace/bin:$PATH

go install github.com/onsi/ginkgo/ginkgo

ginkgo -r -race
