#!/bin/bash

set -e -x

cd $(dirname $0)/..

pushd ~/workspace
  pushd bosh-lite
    if [ "$(bosh -e lite deployments | wc -l)" != "0" ]; then
      vagrant destroy -f
    fi

    vagrant up
    bosh -n -e lite upload-stemcell bosh-stemcell-*.tgz
  popd

  pushd concourse
    bosh -n -e lite create-release --force
    bosh -n -e lite upload-release
  popd

  pushd garden-runc-release
    bosh -n -e lite upload-release $(find releases/garden-runc -name 'garden-runc-*.yml' | sort -rn | head -n1)
  popd
popd

bosh -n -e lite update-cloud-config cloud_config.yml
