#!/bin/bash

set -e -u

cd $(dirname $0)/..

from=${1:-""}

function gh() {
  path=$1
  shift

  curl -sf -H "Authorization: token $GITHUB_TOKEN" https://api.github.com$path "$@"
}

seen_from=false
ls lit/release-notes/*.lit | sort -V | while read path; do
  version=$(basename $path | sed s/.lit//)

  if [ -n "$from" ]; then
    if [ "$version" = "$from" ]; then
      seen_from=true
    fi

    if [ "$seen_from" != "true" ]; then
      echo "skipping $version..."
      continue
    fi
  fi

  echo "updating $version release notes from $path..."

  release_id=$(gh /repos/concourse/concourse/releases/tags/$version | jq -r .id)
  if [ -z "$release_id" ]; then
    echo "unknown release id for $version"
    exit 1
  fi

  jq -n '{body: $body}' --rawfile body <(./scripts/render-release-notes $version) | \
    gh /repos/concourse/concourse/releases/$release_id \
      -XPATCH \
      -H "Content-type: application/json" \
      -d@- | \
      jq -r .html_url

  echo "done"
  echo
done
