#!/bin/bash

set -e
set -u
set -x

JOB_NAME=redis

LOG_DIR=/var/vcap/sys/log/$JOB_NAME
PID_DIR=/var/vcap/sys/run/$JOB_NAME

JOB_DIR=/var/vcap/jobs/$JOB_NAME
PACKAGE_DIR=/var/vcap/packages/$JOB_NAME
DATA_DIR=/var/vcap/store/redis

PID_FILE=$PID_DIR/$JOB_NAME.pid

source /var/vcap/packages/pid_utils/pid_utils.sh

case $1 in
  start)
    mkdir -p $PID_DIR
    mkdir -p $LOG_DIR
    mkdir -p $DATA_DIR

    echo $$ > $PID_FILE

    exec $PACKAGE_DIR/bin/redis-server $JOB_DIR/config/redis.conf \
         >>$LOG_DIR/$JOB_NAME.stdout.log \
         2>>$LOG_DIR/$JOB_NAME.stderr.log
    ;;

  stop)
    ;;
  *)
    echo "Usage: redis_ctl {start|stop}"
    ;;

esac
exit 0