---
platform: linux

image_resource:
  type: registry-image
  source: {repository: golang}

inputs:
- name: docs

caches:
- path: gopath

outputs:
- name: built-docs
  path: docs

params:
  ANALYTICS_ID:
  GITHUB_TOKEN:

run:
  path: docs/ci/build
