#!/bin/bash

set -e -x

# for 'go' on our worker
export PATH=/usr/local/bin:$PATH

export GOPATH=$PWD/gopath:$PWD/concourse:$PWD/gopath/src/github.com/vito/houdini/Godeps_darwin/_workspace
export PATH=$PWD/gopath/bin:$PATH

FINAL_VERSION="$(cat $PWD/final-version/number)"

go get github.com/jteeuwen/go-bindata

go build -o go-bindata github.com/jteeuwen/go-bindata/go-bindata

./go-bindata -pkg bindata -o gopath/src/github.com/concourse/bin/bindata/bindata.go cli-artifacts/...

go build \
  -ldflags "-X github.com/concourse/atc/atccmd.Version=${FINAL_VERSION}" \
  -o darwin-binary/concourse_darwin_amd64 \
  github.com/concourse/bin/cmd/concourse
