#!/bin/bash

set -e -x

export GOPATH=$PWD/gopath:$PWD/concourse:$PWD/guardian-release
export PATH=$PWD/gopath/bin:$PWD/concourse/bin:$PWD/guardian-release:$PATH

FINAL_VERSION="$(cat $PWD/final-version/version)"

go get github.com/jteeuwen/go-bindata/go-bindata

./gopath/src/github.com/concourse/bin/scripts/build-linux

go-bindata -pkg bindata -o gopath/src/github.com/concourse/bin/bindata/bindata.go cli-artifacts/... linux/...

# must be build with 'daemon' flag because of docker packages :|
go build \
  -tags daemon \
  -ldflags "-X github.com/concourse/atc/atccmd.Version=${FINAL_VERSION}" \
  -o binary/concourse_linux_amd64 \
  github.com/concourse/bin/cmd/concourse
