#!/bin/bash

set -e -x

export GOPATH=$PWD/gopath:$PWD/concourse
export PATH=$PWD/gopath/bin:$PWD/concourse/bin:$PATH

go get github.com/jteeuwen/go-bindata/go-bindata

./gopath/src/github.com/concourse/bin/scripts/build-linux

go-bindata -pkg bindata -o gopath/src/github.com/concourse/bin/bindata/bindata.go cli-artifacts/... linux/...

go build -o linux-binary/concourse_linux_amd64 \
  github.com/concourse/bin/cmd/concourse
