#!/bin/bash

set -e -x

echo 'dev' > release/name
echo 'dev' > release/tag

cat > release/body <<EOF
A periodically built release while things are still being worked out.
EOF

mkdir release/artifacts
cp linux-binary/* windows-binary/* darwin-binary/* release/artifacts
