#!/bin/bash

set -e -x

export GOPATH=$PWD/gopath:$PWD/concourse
export PATH=$PWD/gopath/bin:$PWD/concourse/bin:$PATH

go get github.com/jteeuwen/go-bindata/go-bindata

./gopath/src/github.com/vito/concourse-bin/scripts/build

go build -o darwin-binary/concourse_darwin_amd64 \
  github.com/vito/concourse-bin/cmd/concourse
