#!/bin/bash

set -e -u -x

export GOPATH=$PWD/gopath
export PATH=$PWD/gopath/bin:$PATH

cd gopath/src/github.com/concourse/go-concourse

go get -t -d ./...

go install github.com/onsi/ginkgo/ginkgo

ginkgo -r -p
