#!/bin/bash

set -e -x

export GOPATH=$PWD/concourse:$PWD/garden-runc-release
export PATH=$PWD/concourse/bin:$PWD/garden-runc-release:$PATH

FINAL_VERSION="0.0.0"
WORKER_VERSION="0.0.0"

cp -R web concourse/src/github.com/concourse/web

mkdir cli-artifacts

go get github.com/jteeuwen/go-bindata/go-bindata

./concourse/src/github.com/concourse/bin/scripts/build-linux

go-bindata -nomemcopy -pkg bindata -o concourse/src/github.com/concourse/bin/bindata/bindata.go cli-artifacts/... assets/...

go build \
  -tags daemon \
  -ldflags "-X main.Version=${FINAL_VERSION} -X github.com/concourse/atc/atccmd.Version=${FINAL_VERSION} -X github.com/concourse/atc/atccmd.WorkerVersion=${WORKER_VERSION} -X main.WorkerVersion=${WORKER_VERSION}" \
  -o concourse_linux_amd64 \
  github.com/concourse/bin/cmd/concourse

sha1sum concourse_linux_amd64 > concourse_linux_amd64.sha1

CONCOURSE=$PWD/concourse_linux_amd64
chmod +x $CONCOURSE

/etc/init.d/postgresql start
yes "" | su postgres -c "createuser -s -P $(whoami)"
createdb atc

function wait_for_proc_port() {
  name=$1
  pid=$2
  port=$3

  until nc -w1 127.0.0.1 $port </dev/null; do
    if ! kill -0 $pid; then
      echo "${name} exited; aborting"
      exit 1
    fi

    echo "waiting for ${name}..."
    sleep 1
  done
}

$CONCOURSE quickstart \
    --postgres-socket /var/run/postgresql \
    --log-level debug \
    --add-local-user 'test:$2a$10$GXdnc1kAKG2u1Ba5DOO1G.uPADrfqr/ifudwHG/pTSUnKj/QQfi8i' \
    --main-team-allow-all-users \
    --worker-work-dir /scratch/concourse \
    --worker-garden-network-pool 10.255.0.0/22 \
    &

quickstartpid=$!

wait_for_proc_port atc $quickstartpid 8080
wait_for_proc_port tsa $quickstartpid 2222
wait_for_proc_port garden $quickstartpid 7777
wait_for_proc_port baggageclaim $quickstartpid 7788

export ATC_URL=http://127.0.0.1:8080
export ATC_USERNAME=test
export ATC_PASSWORD=test

export GEM_HOME=${PWD}/gems
export BUNDLE_PATH=${PWD}/gems

go install github.com/concourse/fly

export DISPLAY=:99.0
Xvfb $DISPLAY -ac +extension RANDR &
trap "kill $!" EXIT

cd concourse/src/github.com/concourse/web/acceptance/
bundle
if ! bundle exec parallel_rspec spec -o "--tag ~perf"; then
  echo "************ RERUNNING FAILURES ************"
  bundle exec rspec $(grep "rspec ./spec" /tmp/failing_specs.log | cut -d' ' -f2 | grep -o ".*:[0-9]\+")
fi
