#!/bin/bash

set -e -x -u

CONCOURSE=$PWD/linux-binary/concourse_linux_amd64
chmod +x $CONCOURSE

# start postgres and set up passwordless superuser
/etc/init.d/postgresql start
yes "" | su postgres -c "createuser -s -P $(whoami)"
createdb atc

function wait_for_proc_port() {
  name=$1
  pid=$2
  port=$3

  until nc -w1 127.0.0.1 $port </dev/null; do
    if ! kill -0 $pid; then
      echo "${name} exited; aborting"
      exit 1
    fi

    echo "waiting for ${name}..."
    sleep 1
  done
}

webpid=1
workerpid=1

if [ "$QUICKSTART" = "true" ]; then
  $CONCOURSE quickstart \
    --postgres-socket /var/run/postgresql \
    --log-level debug \
    --no-really-i-dont-want-any-auth \
    --worker-work-dir /scratch/concourse \
    --worker-garden-network-pool 10.255.0.0/22 \
    &

  quickstartpid=$!

  wait_for_proc_port atc $quickstartpid 8080
  wait_for_proc_port tsa $quickstartpid 2222
  wait_for_proc_port garden $quickstartpid 7777
  wait_for_proc_port baggageclaim $quickstartpid 7788
else
  # set up keys
  mkdir /etc/concourse
  ssh-keygen -f /etc/concourse/tsa-host -N ''
  ssh-keygen -f /etc/concourse/worker -N ''
  ssh-keygen -f /etc/concourse/session-signing-key -N ''

  $CONCOURSE web \
    --postgres-socket /var/run/postgresql \
    --tsa-host-key /etc/concourse/tsa-host \
    --tsa-authorized-keys /etc/concourse/worker.pub \
    --session-signing-key /etc/concourse/session-signing-key \
    --log-level debug \
    --no-really-i-dont-want-any-auth \
    &

  webpid=$!

  wait_for_proc_port atc $webpid 8080
  wait_for_proc_port tsa $webpid 2222

  $CONCOURSE worker \
    --work-dir /scratch/concourse \
    --tsa-worker-private-key /etc/concourse/worker \
    --tsa-public-key /etc/concourse/tsa-host.pub \
    --garden-network-pool 10.255.0.0/22 \
    > /tmp/worker.log \
    &

  workerpid=$!
  wait_for_proc_port garden $workerpid 7777
  wait_for_proc_port baggageclaim $workerpid 7788
fi


export ATC_URL=http://127.0.0.1:8080

./concourse/ci/scripts/testflight "$@"
