#!/bin/bash

set -e -x -u

CONCOURSE=$PWD/linux-binary/concourse_linux_amd64
chmod +x $CONCOURSE

# start postgres and set up passwordless superuser
/etc/init.d/postgresql start
su postgres -c "createuser -s -P $(whoami)"
createdb atc

# set up keys
mkdir /etc/concourse
ssh-keygen -f /etc/concourse/tsa-host -N ''
ssh-keygen -f /etc/concourse/worker -N ''
ssh-keygen -f /etc/concourse/session-signing-key -N ''

function wait_for_proc_port() {
  name=$1
  pid=$2
  port=$3

  until nc -w1 127.0.0.1 $port </dev/null; do
    if ! kill -0 $pid; then
      echo "${name} exited; aborting"
      exit 1
    fi

    echo "waiting for ${name}..."
    sleep 1
  done
}

# don't leak client id/secret
set +x

github_auth_config=""
if [ -n "$GITHUB_AUTH_CONFIG_ORGANIZATION" ]; then
  github_auth_config="$github_auth_config --github-auth-organization $GITHUB_AUTH_CONFIG_ORGANIZATION"
fi

$CONCOURSE web \
  --external-url "http://$(hostname -i):8080" \
  --oauth-base-url "http://127.0.0.1:8080" \
  --tsa-host-key /etc/concourse/tsa-host \
  --tsa-authorized-keys /etc/concourse/worker.pub \
  --session-signing-key /etc/concourse/session-signing-key \
  --development-mode \
  --resource-checking-interval 5s \
  --basic-auth-username "$BASIC_AUTH_USERNAME" \
  --basic-auth-password "$BASIC_AUTH_PASSWORD" \
  --github-auth-client-id "$GITHUB_AUTH_CONFIG_CLIENT_ID" \
  --github-auth-client-secret "$GITHUB_AUTH_CONFIG_CLIENT_SECRET" \
  $github_auth_config \
  &

# reenable tracing now that atc is launched
set -x

webpid=$!

wait_for_proc_port web $webpid 8080

$CONCOURSE worker \
  --work-dir /etc/concourse \
  --tsa-worker-private-key /etc/concourse/worker \
  --tsa-public-key /etc/concourse/tsa-host.pub \
  --garden-network-pool 10.255.0.0/22 \
  > /tmp/worker.log \
  &

workerpid=$!

wait_for_proc_port worker $workerpid 7777

export ATC_URL=http://127.0.0.1:8080

./concourse/ci/scripts/testflight "$@"
