// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/concourse/atc/worker"
	"github.com/concourse/baggageclaim"
)

type FakeVolumeFactory struct {
	BuildStub        func(baggageclaim.Volume) (worker.Volume, error)
	buildMutex       sync.RWMutex
	buildArgsForCall []struct {
		arg1 baggageclaim.Volume
	}
	buildReturns struct {
		result1 worker.Volume
		result2 error
	}
}

func (fake *FakeVolumeFactory) Build(arg1 baggageclaim.Volume) (worker.Volume, error) {
	fake.buildMutex.Lock()
	fake.buildArgsForCall = append(fake.buildArgsForCall, struct {
		arg1 baggageclaim.Volume
	}{arg1})
	fake.buildMutex.Unlock()
	if fake.BuildStub != nil {
		return fake.BuildStub(arg1)
	} else {
		return fake.buildReturns.result1, fake.buildReturns.result2
	}
}

func (fake *FakeVolumeFactory) BuildCallCount() int {
	fake.buildMutex.RLock()
	defer fake.buildMutex.RUnlock()
	return len(fake.buildArgsForCall)
}

func (fake *FakeVolumeFactory) BuildArgsForCall(i int) baggageclaim.Volume {
	fake.buildMutex.RLock()
	defer fake.buildMutex.RUnlock()
	return fake.buildArgsForCall[i].arg1
}

func (fake *FakeVolumeFactory) BuildReturns(result1 worker.Volume, result2 error) {
	fake.BuildStub = nil
	fake.buildReturns = struct {
		result1 worker.Volume
		result2 error
	}{result1, result2}
}

var _ worker.VolumeFactory = new(FakeVolumeFactory)
