#!/bin/bash

set -e -x

echo "v$(cat version/version)" > release/name
echo "v$(cat version/version)" > release/tag

cat > release/body <<EOF
A candidate release that has yet to be vetted by our full pipeline.

You may want to look at [the concourse/concourse releases](https://github.com/concourse/concourse/releases) instead.
EOF

mkdir release/artifacts

for platform in linux windows darwin; do
  cp ${platform}-binary/* release/artifacts
done
