#!/bin/bash

set -e -u -x

export GOPATH=$PWD/concourse
export PATH=$PWD/concourse/bin:$PATH

export PR_REPO=$PWD/fly

pushd fly
  git checkout -b pr
popd

cd concourse/src/github.com/concourse/fly

git remote add pr $PR_REPO
git fetch pr
git checkout pr/pr

go get -t -d ./...

go install github.com/onsi/ginkgo/ginkgo

ginkgo -r -p -race "$@"
