#!/bin/bash

set -e -u

source $(dirname $0)/common.bash

cd $(dirname $0)/../..

./dev/vbox/deploy

by "running testflight..."
cd ./src/github.com/concourse/testflight
ATC_URL="http://10.244.15.2:8080" \
  ginkgo -r -p -nodes=3 "$@"
